### ISSUE TITLE
I am not in any group 

### ISSUE THREAD

**Issue by khamidovov** [Chingu-cohorts/voyage-wiki#102]
**_About You_**
- Team Name: I don’t have one yet
- Slack Name: Akbar
- Timezone: UTC+9

**_Issue Description & Expected Outcome:_** 
I haven’t been added to any group yet & wanna be added if still possible 
**_Symptoms:_**
I have no idea why
**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
For transparency: 

Member did not fill out form before teams were deployed, wasn't placed in a team. 

We found him a team last minute. Ticket closed 🚀
