### ISSUE TITLE
change the team & need to be PM

### ISSUE THREAD

**Issue by hamedshahien** [Chingu-cohorts/voyage-wiki#103]
**_About You_**
Hamed from Egypt 5+ years experience lamp stack 
- Team Name: 
Bears-team-16
- Slack Name: 
hamedshahien
- Timezone: 
gmt+2
**_Issue Description & Expected Outcome:_** 
I have only 2 people in the team and they are from my culture , I need to meet new friends from other cultures. this is the goal . may be English , French , German countries. also  I need to be assigned the role of project manager if it's available .

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
DM sent.
