### ISSUE TITLE
Not part of any group

### ISSUE THREAD

**Issue by karthikgg** [Chingu-cohorts/voyage-wiki#104]
**_About You_**
- Team Name: 
N/A
- Slack Name: 
@Karthik G
- Timezone: 
GMT-7 (California, USA)
**_Issue Description & Expected Outcome:_** 
I am not part of any group. Unfortunately, I missed filling out the team form. I have filled it up now.
My email id is karthik@bombaylove.com

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Thank @karthikgg - I see you've filled out the form and once a spot opens up we'll let you know. 👍

**Comment by hamedshahien** [comment]
could he join our team ?  our team is 3 persons . one of us not replying .I can't imagine team of only 2 persons.  I think even he reply we can be 4 person in the team.  
#bears-team-16

**Comment by tropicalchancer** [comment]
You can ask him @hamedshahien - there is a big time difference so make sure everyone understands that before going forward. 

Let me know.

**Comment by hamedshahien** [comment]
hi @karthikgg . I sent you slack DM. If you need to join us . Just let us know.

**Comment by hamedshahien** [comment]
@tropicalchancer he joined us to channel #bears-team-16
