### ISSUE TITLE
Don’t have a team assigned 

### ISSUE THREAD

**Issue by MauricioS93** [Chingu-cohorts/voyage-wiki#105]
**_About You_**
- Team Name: none
- Slack Name: Msarmiento
- Timezone: Pacific time

**_Issue Description & Expected Outcome:_** 
I have not been assigned a group. My email is: micho.sarmieto.b@gmail.com and I have filled the application form a while ago. 
Thank you. 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Added to a team 🎉
