### ISSUE TITLE
Not part of a team

### ISSUE THREAD

**Issue by mrbrackins** [Chingu-cohorts/voyage-wiki#106]
**_About You_**
- Team Name:  n/a
- Slack Name:  @mrbrackins
- Timezone: PST

**_Issue Description & Expected Outcome:_** 
Supposed to be on a team. Field out form.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Added to a team 🎉
