### ISSUE TITLE
Our teammate is not showing up

### ISSUE THREAD

**Issue by khamidovov** [Chingu-cohorts/voyage-wiki#109]
**_About You_**
- Team Name: geckos-team-45
- Slack Name: Akbar
- Timezone: UTC+9

**_Issue Description & Expected Outcome:_** 
Our teammate is not replying 
Want somebody else 
**_Symptoms:_**
No idea
**_Steps to Recreate:_** 

**_Resolution:_** 
Plz add one gecko to geckos-team-45

**Comment by tropicalchancer** [comment]
Hey @khamidovov 

Thanks for making a ticket. 

Have you reached out to the person via Direct Message? If not please do that to see what the person's commitment level for this cohort is and let us know.

**Comment by tropicalchancer** [comment]
Have an addition to team if need be. Waiting to hear back :)
