### ISSUE TITLE
Two Members are not in team standups

### ISSUE THREAD

**Issue by SumanKisku** [Chingu-cohorts/voyage-wiki#11]
**_Issue Description & Expected Outcome:_** 
My two members are not in team standup. One(neo) of them is not responding to my DMs. And have not seen other one(akash) online. Toucans team 12.
**_Symptoms:_**
![screenshot 10](https://user-images.githubusercontent.com/7936345/36341732-d7d7c542-1418-11e8-8b57-89c1be726a44.png)

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by jdmedlock** [comment]
Researching this issue. Will post status shortly.

**Comment by jdmedlock** [comment]
Update. We've verified that both have been invited to Slack and I can see that `neo` is currently online (11:05 a.m. CST). I'm reaching out to both to ask them to connect with you on Slack. They will also receive emails when we add them to your GitHub team this weekend. If they don't respond to Slack then hopefully the GitHub email will prompt them to reach out to you.

It sometimes takes a couple days for team members to connect based on their work and family schedules. However, if they haven't made contact with you by Monday then we'll revisit this issue.

**Comment by jdmedlock** [comment]
Leaving this issue open until Monday

**Comment by jdmedlock** [comment]
Update. Neo has made contact and is participating in the Toucans-Team-12 team, but there is still no word from Akash.

**Comment by tropicalchancer** [comment]
Hi @SumanKisku! 

The reason the other team members are set as Null is because they likely have no registered on chingu.io and authenticated their account in slack. 

If the team becomes active we can settle this in the coming days.

**Comment by tropicalchancer** [comment]
Have messaged @SumanKisku. When I get the go-ahead I'll close this ticket.
