### ISSUE TITLE
Add recommended deadlines to Voyage Roadmap

### ISSUE THREAD

**Issue by Double-A-92** [Chingu-cohorts/voyage-wiki#110]
**_About You_**
* Slack Name: Amedeo

**_Issue Description & Expected Outcome:_** 
https://github.com/Chingu-cohorts/pmrok/wiki/Voyage-Roadmap should include recommended / expected deadlines for each task.

**_Symptoms:_**
Difficulties while planning our next steps with the team.

**_Steps to Recreate:_** 
None

**_Resolution:_** 
Add average durations to the tasks, and relative deadlines (e.g. "1st week", "2nd to 3rd week") to the acts.

**Comment by tropicalchancer** [comment]
Talked to person helping with wiki and this will be included in the updated wiki. 💯
