### ISSUE TITLE
Inactive team member in Geckos-Team-34

### ISSUE THREAD

**Issue by adeen-s** [Chingu-cohorts/voyage-wiki#111]
**_About You_**
- Team Name: geckos-team-34
- Slack Name: adeen-s
- Timezone: UTC +5:30 India

**_Issue Description & Expected Outcome:_** 
One member of our team, Dani Vijay, has not yet replied to any messages in team chat. He is also my pair programming partner and I haven't heard from him there too since his initial introductory message on the day the pair was made. We have mentioned him multiple times in team chat and even sent a Direct Message but no reply yet.

**Comment by tropicalchancer** [comment]
Removed Dani Vijay and added a new member. Ticket closed 🚀
