### ISSUE TITLE
Inactive member in geckos-team-10

### ISSUE THREAD

**Issue by rafaelmollad** [Chingu-cohorts/voyage-wiki#113]
**_About You_**
- Team Name: geckos-team-10
- Slack Name: Rafaelmolladouglas
- Timezone: UTC -3

**_Issue Description & Expected Outcome:_** 
The team member Stacy (Stacykillinger) has been inactive since the team was set up. We didn't even get one message from her. We'd like to get another team member please.

**Comment by tropicalchancer** [comment]
New member added.
