### ISSUE TITLE
Not received git repo mail.

### ISSUE THREAD

**Issue by adsingh14** [Chingu-cohorts/voyage-wiki#116]
**_About You_**
- Team Name: toucans 
- Slack Name: Aman
- Timezone: UTC +5

**_Issue Description & Expected Outcome:_** 
As I read the recent announcement about github repo for teams. 
But I(maybe other user) have not recieved githib repo mail connected with my chingu registered account.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
In how many days, all of us will recieve github invitation mail?

**Comment by tropicalchancer** [comment]
Just checked and you've been added!
