### ISSUE TITLE
Did not receive the invite to team repo

### ISSUE THREAD

**Issue by ElleeB** [Chingu-cohorts/voyage-wiki#119]
**_About You_**
- Team Name: Bears-Team-3
- Slack Name: Laura Trager
- Timezone: 

**_Issue Description & Expected Outcome:_** 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Checked repo and it appears you have already accepted the invite so it much have worked itself out? 🎉
