### ISSUE TITLE
Chingu GitHub ID's not recognized by GitHub

### ISSUE THREAD

**Issue by jdmedlock** [Chingu-cohorts/voyage-wiki#12]
**_Issue Description & Expected Outcome:_** 
The following Chingu user id's were not recognized by GitHub during team definition in Voyage4 Organization.

| Team Name |GitHub Id Provided |
|:------------|:-------------------|
| Bears-44    | jdmedlock <-- Example |

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by jdmedlock** [comment]
All GitHub repos and teams have been set up as of 2/18/2018 @ 09:00 CST so there should be no more additions to the list above.

**Comment by tropicalchancer** [comment]
Completed.
