### ISSUE TITLE
How can I accept the Github invite

### ISSUE THREAD

**Issue by yapanss** [Chingu-cohorts/voyage-wiki#120]
**_About You_**
- Team Name: Gecko-Team-25
- Slack Name: Assi
- Timezone: UTC+0

**_Issue Description & Expected Outcome:_** 
I received the Email, connected to Github, but don't know how to accept th invite
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hey @yapanss it should be a link you can click in the email. 

I'll send a DM and we can troubleshoot it.
