### ISSUE TITLE
Needs a team

### ISSUE THREAD

**Issue by TatyCat** [Chingu-cohorts/voyage-wiki#122]
**_About You_**
- Team Name: gecko-8
- Slack Name: tatyanna
- Timezone: ny

**_Issue Description & Expected Outcome:_** 
2/3 of the gecko-8 group have left

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** Need a new team.

**Comment by tropicalchancer** [comment]
Added to a new team 🎉
