### ISSUE TITLE
Missing team members 

### ISSUE THREAD

**Issue by yapanss** [Chingu-cohorts/voyage-wiki#125]
**_About You_**
- Team Name: Gecko-25
- Slack Name: Assi
- Timezone: UTC

**_Issue Description & Expected Outcome:_** 
My teammates are unreachable. 
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
Assign new teammates

**Comment by tropicalchancer** [comment]
Made an effort to get the team up and running. If the team fails to get the project setup in the next week, please make another ticket 🙏
