### ISSUE TITLE
Team member inactive

### ISSUE THREAD

**Issue by Zappy555** [Chingu-cohorts/voyage-wiki#126]
**_About You_**
- Team Name: Toucans_Team_17
- Slack Name: Zandas512
- Timezone: GMT+1 (Lagos)

**_Issue Description & Expected Outcome:_** 
I was teamed up with a member (Slack UN: @cosmic). He opened communication and I responded. Planned to talk more ASAP and that was the last I heard from him. It's over 72hrs and no word from him despite my best effort to resume project plan and execution.

I want to be placed in another team as we were just two in the team.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Thanks for making a ticket @Zappy555! 

Have a potential solution and sent a DM in slack. Will act once I get a reply.

**Comment by tropicalchancer** [comment]
Added to a new team! 🎉
