### ISSUE TITLE
Team member inactive

### ISSUE THREAD

**Issue by LaurenDoughty** [Chingu-cohorts/voyage-wiki#128]
**_About You_**
- Team Name: toucans-team-06
- Slack Name: laurend
- Timezone: Eastern

**_Issue Description & Expected Outcome:_** 
SethAyers has been inactive, was active over the weekend a little bit but not at all during the week
haven't been able to set up meeting times or have a meeting or decide on a project

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
it's his first Chingu, I leave the resolution in your hands as I don't know how to best proceed here

**Comment by tropicalchancer** [comment]
Will remove if no reply.
