### ISSUE TITLE
Update Team Membership in Bears-Team-9

### ISSUE THREAD

**Issue by pkshreeman** [Chingu-cohorts/voyage-wiki#129]
**_About You_**
- Team Name: Chingu Voyage-5 Bears-Team-9
- Slack Name: Paul Shreeman
- Timezone: CA

Currently, Luis Jimenez which is on my Slack's bears-team-09 is not invited (?) or is not a member of https://github.com/orgs/chingu-voyage5/teams/bears-team-9?  

Also,  Eric H has transferred to a different team, so I recommend removing his membership in this repo as well?

Thank you.

Paul

**Comment by tropicalchancer** [comment]
Thanks for making a ticket @pkshreeman! 

Eric has been removed & it appears Luis has accepted his invite.
