### ISSUE TITLE
Wizard Team Standup giving error

### ISSUE THREAD

**Issue by lucygracesmom** [Chingu-cohorts/voyage-wiki#13]
![screenshot 1](https://user-images.githubusercontent.com/24363054/36345584-a20e142e-13fb-11e8-9751-4549a318b920.png)
When I run /team progress the Team Standups box is not shaded and when I click on it I get the error that's shown in the picture.  You all are doing such great work!  There is so much assistance.  I am so thankful!

**Comment by jdmedlock** [comment]
`Team Standups`  displays previously completed standups. Have you performed a `New Standup`?

**Comment by jdmedlock** [comment]
Please update `lucygracesmom` to be a co-PM on her team with @jesica (Slack name)/ jessiepenaloza (GitHub name)

**Comment by the-vampiire** [comment]
@lucygracesmom you are now both PM of your team with shared PM privelages
