### ISSUE TITLE
Not Included In Repository; gecko-41

### ISSUE THREAD

**Issue by chromity** [Chingu-cohorts/voyage-wiki#130]
**_About You_**
- Team Name: gecko-41
- Slack Name: michael daryl mayo
- Timezone: gmt +8

**_Issue Description & Expected Outcome:_** not included in team repo

**_Symptoms:_**

**_Steps to Recreate:_**  check the repo for gecko-41

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Thanks for making a ticket @chromity! 

I just checked and you were invited to the team repo, and it says your invite is still pending. 

Please make sure to check the email connected to your github account.

**Comment by chromity** [comment]
hello,

can't find it. can you invite me using my username instead?
