### ISSUE TITLE
Authorize TravisCI integration

### ISSUE THREAD

**Issue by mepda** [Chingu-cohorts/voyage-wiki#133]
**_About You_**
- Team Name: Gecko43
- Slack Name:  lePancake
- Timezone: Korea

**_Issue Description & Expected Outcome:_** 
Authorize me/my team for TravisCI integration into github
**_Symptoms:_**
Currently not able to authorize TravisCI into this repo
**_Steps to Recreate:_** 
I think adding me to the organization should allow me to setup TravisCI into our project
**_Resolution:_** 
Not sure what that means, but none yet

**Comment by tropicalchancer** [comment]
Hey @mepda! 

Done! Let me know if there any issues. 🌮
