### ISSUE TITLE
Team change 

### ISSUE THREAD

**Issue by ghost** [Chingu-cohorts/voyage-wiki#134]
**_About You_**
- Team Name: geckos_team_02
- Slack Name: andrewriveraj
- Timezone: Central 

**_Issue Description & Expected Outcome:_** 
Teammates are not available and rarely come online. I could work on the project alone, but I prefer working on a team. Therefore, I would like to transfer to another team. 
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by brandonvernon** [comment]
Hey Andrew! Does the gecko represent tier 2 or intermediate?  If so I'd love to join your team or you join mine. We're a toucan team but I believe we're more advanced. We need a team lead. My teammate is fine but he's only available when I'm not and he seems very busy. I just posted a ticket of my own.

**Comment by ghost** [comment]
Let’s do it!
