### ISSUE TITLE
Inactive team member

### ISSUE THREAD

**Issue by TatyCat** [Chingu-cohorts/voyage-wiki#136]
**_About You_**
- Team Name:  toucans 6
- Slack Name: tatyanna
- Timezone: fl/eastern

**_Issue Description & Expected Outcome:_** 

**_Symptoms:_**
Seth ayers has been inactive prior to me joining the team and contines to be inactive. 

**_Steps to Recreate:_** 

**_Resolution:_** T6 needs fresh blood :)

**Comment by slouischarles** [comment]
Has your team picked a project or team lead? How many members and is everyone active? I ask because I may have a problem with my team as I've talked to one member once.

**Comment by tropicalchancer** [comment]
@slouischarles has been added
