### ISSUE TITLE
Due date for MVP clarification

### ISSUE THREAD

**Issue by pkshreeman** [Chingu-cohorts/voyage-wiki#137]
**_About You_**
- Team Name:  Bears09
- Slack Name: Paul Shreeman
- Timezone: CA

I am confused to when the MVP is due.  From two sources (Trello's Voyage Schedule), and [FAQ](https://medium.com/chingu/so-youve-been-placed-in-a-chingu-developer-team-read-this-faq-53e3303c23b0) states that MVP is due on 20th, but this [Medium's Article]https://medium.com/chingu/voyage-5-prep-overview-of-what-you-need-to-know-e6c3ea2cefc5) states that MVP is due on July 15th?

Can you please let me determine what is the due date for MVP completion?  

Thank you!

**Comment by tropicalchancer** [comment]
Thanks so much for letting me know about this @pkshreeman! 🙏 

The MVP due date is July 20th. I've fixed it in the Medium article.
