### ISSUE TITLE
Change project manager

### ISSUE THREAD

**Issue by kahwasaurus** [Chingu-cohorts/voyage-wiki#14]
**_Issue Description & Expected Outcome:_** 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
I have been assigned the project manager role but we had decided on "Marylicious".  How can we change it?

**Comment by jdmedlock** [comment]
Response from Vannya in #wizard-issues channel to @leahk - "We will get it switched over, but everyone is sleeping or running in and out today.  If you'll make a ticket, we will take care of y'all with no issues"

**Comment by jdmedlock** [comment]
Waiting on guidance from Wizard Team

**Comment by the-vampiire** [comment]
@jdmedlock fixed
