### ISSUE TITLE
Need to add new member to our GitHub Team

### ISSUE THREAD

**Issue by jmaldia** [Chingu-cohorts/voyage-wiki#140]
**_About You_**
- Team Name: Geckos 0
- Slack Name: jon-maldia
- Timezone: EST

**_Issue Description & Expected Outcome:_** 
We have a new team member. @kiranS on slack. We need to add him to our GH team. @kiranshuaib on Github.

**Comment by tropicalchancer** [comment]
Invite was sent and is currently pending. 🌮
