### ISSUE TITLE
Need new and more advanced team or more teammates

### ISSUE THREAD

**Issue by brandonvernon** [Chingu-cohorts/voyage-wiki#142]
**_About You_**
- Team Name: toucans-team-03
- Slack Name: Brandon Vernon
- Timezone: UTC-5

**_Issue Description & Expected Outcome:_** 
Didn't expect to be set up with only one person. I had hoped to work on a team of 3 or more. I definitely don't want to be the team lead. My partner is also much busier than me and can really only meet late at night (for my timezone) and late nights aren't best for me.  We also haven't been able to discuss our project yet because he was busy all last week and I was away this weekend. On top of all that I believe I should be in tier 2 instead (I don't know which animal that represents). I'd like to be on a team of at least 3 and have that team be a tier 2 (or a really advanced tier 1). My teammate is more than welcome to stay my teammate - it just won't out if it remains just us.
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by omoosey** [comment]
Just chiming in to say we spoke on Slack and agree that we both would like to be part of a larger team to work on something bigger than just a landing page. I am definitely busy on weekdays (10 hours at work) but I can get hours in on the project during the weekend and whatever spare time I have after work.
