### ISSUE TITLE
Need access to team bears 04

### ISSUE THREAD

**Issue by exsqzme** [Chingu-cohorts/voyage-wiki#143]
**_About You_**
- Team Name: bears 04
- Slack Name: exSQZme
- Timezone: utc-5

**_Issue Description & Expected Outcome:_** 
Need access to team bears 04
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @likeMike! 

You've been added to Bears 04. Please check your email connected to your github account.  🌮
