### ISSUE TITLE
Losing team member Toucans_02

### ISSUE THREAD

**Issue by ZumDeWald** [Chingu-cohorts/voyage-wiki#144]
**_About You_**
- Team Name: Toucans_02
- Slack Name: Z
- Timezone: Central (UTC -6)

**_Issue Description & Expected Outcome:_** 
  My only team member, Dean, has let me know he will not be continuing on this voyage. Is it possible to get assigned another? I will continue on and complete a project with teammates or not, but the greatest part of Chingu is the people!!

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Perseverance award goes to Z, who has blazed ahead!
