### ISSUE TITLE
not in team github

### ISSUE THREAD

**Issue by clickingmouse** [Chingu-cohorts/voyage-wiki#145]
**_About You_**
- Team Name: bears-team30
- Slack Name: kevin Ko
- Timezone: 

**_Issue Description & Expected Outcome:_** 
not part of the team's github, hence, cant clone team's repo
**_Symptoms:_**
my github account is clickingmouse
**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hey @clickingmouse! 

Thanks for making a ticket. Your github invite was sent last week and is still pending (I just checked). 

Please check the settings on your github account and make sure you're checking the email connected to your github account.
