### ISSUE TITLE
Team Transfer

### ISSUE THREAD

**Issue by ibrahimbutt** [Chingu-cohorts/voyage-wiki#146]
**_About You_**
- Team Name: Bears 13
- Slack Name: ibrahim
- Timezone: GMT+1

**_Issue Description & Expected Outcome:_** 
My team members were inactive and I was in touch with Simon (Jakku on Slack), as I wanted to help with the not-for-profit project. He got me a spot on Bears 30. 

I need to be taken off the Bears 13 team on GitHub and added to Bears 30.

**Comment by tropicalchancer** [comment]
Hi @IbrahimButt! 

Added!
