### ISSUE TITLE
Inactive Team Member

### ISSUE THREAD

**Issue by dirkduplooy** [Chingu-cohorts/voyage-wiki#147]
**_About You_**
- Team Name: Toucans-13
- Slack Name: dirkduplooy
- Timezone: UCT +2

**_Issue Description & Expected Outcome:_** 
Hi Chance it seems user @Avic Studio is not active
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
Can you find out if he is going to be part of the Voyage as we did reach out in Slack to him but it does not seem he is responding, thanks

**Comment by tropicalchancer** [comment]
Could be solved, just waiting to hear back 🌮
