### ISSUE TITLE
Switched Teams. Need access to Team's Repo. 

### ISSUE THREAD

**Issue by andrwsalcdo** [Chingu-cohorts/voyage-wiki#148]
**_About You_**
- Team Name: geckos-team-27
- Slack Name:  andrew
- Timezone:  GMT + 2

**_Issue Description & Expected Outcome:_** 
I only have repo pull access to old team's repo (bears 13). I need access to geckos team 27, please. 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Done thanks for making a ticket @andrwsalcdo 🌮
