### ISSUE TITLE
Team Unresponsive

### ISSUE THREAD

**Issue by jmaldia** [Chingu-cohorts/voyage-wiki#15]
**_Issue Description & Expected Outcome:_** 
Two of my teammates have not responded in our team channel (toucans-team-5). One of them is the project manager. The other is not on chat. 

There are 2 of us that are active right now. 

Thanks. 

**_Symptoms:_**
**_Steps to Recreate:_** 
**_Resolution:_**

**Comment by jdmedlock** [comment]
Toucans-Team-5 consists of the following members:

- AbhiRKeesara
- starkspark
- Jmaldia
- zaynaib

**Comment by jdmedlock** [comment]
Let's give this until tomorrow morning EST to see if they join. If no response by tomorrow I'll add your team to the list of teams requiring repair this week.

**Comment by jmaldia** [comment]
Thanks @jdmedlock.

**Comment by jmaldia** [comment]
Just want to update you. 
AbhiRKeesara - not active
starkspark - not active
Jmaldia - active
zaynaib - active

**Comment by jmaldia** [comment]
Update: 

starkspark - not active
AbhiRKeesara - active
Jmaldia - active
zaynaib - active

**Comment by tropicalchancer** [comment]
I talked to @jmaldia and this ticket is closed for now (as the PM is now there), but he will reach out with a new ticket if anything changes.
