### ISSUE TITLE
Lost Team Member / Move Teams

### ISSUE THREAD

**Issue by nroode** [Chingu-cohorts/voyage-wiki#150]
**_About You_**
- Team Name: Geckos-team-15
- Slack Name: natalieR, imcodingideas
- Timezone: UTC-8

**_Issue Description & Expected Outcome:_** 
Our team member jProgr let us know that he has to leave the team so we are down to two.  

After talking it over, it sounds like a tier-3 team may be better aligned with the skills and interests of my teammate, imcodingideas while I am happy on a tier-2 team.  Would it be possible for us to join other teams? 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by imcodingideas** [comment]
Hello, we're `geckos-team-15` and I would like to be put in a `Tier 3` timezone: GMT-7. I saw `Bears-Team-30` and it looks fun but I would like to be on a team where we're doing something full-stack.

**Comment by tropicalchancer** [comment]
@imcodingideas please send @tony a message in slack. He's looking for a new tier-3 member for his team 🎉

**Comment by tropicalchancer** [comment]
@nroode message sent in slack with potential solution
