### ISSUE TITLE
Inactive Team member

### ISSUE THREAD

**Issue by Anshul2166** [Chingu-cohorts/voyage-wiki#152]
**_About You_**
- Team Name: Bears Team 25
- Slack Name: Anshul
- Timezone: UTC+5.30

**_Issue Description & Expected Outcome:_** One member Abdelrhman has been inactive from around 10 days. We were a group of 3 but now are down to 2.

**_Symptoms:_** He has been inactive in the group and showing no response even when tagged. We tried to DM him but has not replied to it also.

**_Steps to Recreate:_** 

**_Resolution:_** 
Please assign another member in his place if possible.

**Comment by tropicalchancer** [comment]
Merged with @amadeo & @spaghettithotts 🎉
