### ISSUE TITLE
Lost team member

### ISSUE THREAD

**Issue by bennythejudge** [Chingu-cohorts/voyage-wiki#153]
**_About You_**
- Team Name: geckos-team-22
- Slack Name: blg
- Timezone: CEST

**_Issue Description & Expected Outcome:_** 
Team member Anirudh is withdrawing from the voyage.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
@bennythejudge  please reach out to @amedeo on slack or @spaghettithots as they are looking for a new team-mate(s). Cheers!

**Comment by bennythejudge** [comment]
@tropicalchancer will you be removing Anirudh from the team slack channel?
