### ISSUE TITLE
Is there any team working on an Android project and could I be moved there?

### ISSUE THREAD

**Issue by bennythejudge** [Chingu-cohorts/voyage-wiki#154]
**_About You_**
- Team Name: geckos-team-22
- Slack Name: blg
- Timezone: CEST

**_Issue Description & Expected Outcome:_** 
Is there any team working on Android? if yes, could I join that team?

Thanks

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
@bennythejudge there is no team working on an Android project as far as I know
