### ISSUE TITLE
Facing challenges in integration of Wafflebot with Github.

### ISSUE THREAD

**Issue by KirankumarAmbati** [Chingu-cohorts/voyage-wiki#155]
**_About You_**
- Team Name: **Geckos-Team-39**
- Slack Name: **kirankumarambati**
- Timezone: + 5:30 GMT

**_Issue Description:_** 

Whenever I'm trying to integrate WaffleBot with Github, I'm not able to find any repo in CHingu Organization. As a result, WaffleBot configuration is halted.

**_Expected Outcome:_**

I should be able to integrate WaffleBot with my Chingu repo.

**_Symptoms:_**

- [Screenshot-1](https://drive.google.com/open?id=1k-2IlG21uiI0iK2Mrt7EE80YBwCbCLXz)

- [Screenshot-2](https://drive.google.com/open?id=14mLakdx-yFZIw7ra0A027xCqXmhYPrGO)

- [Screenshot-3](https://drive.google.com/open?id=1oituvdSnAtkrA6TNcQ9cNtQ8KgpFXBeE)

**_Resolution:_** 
Yet to find out.

**Comment by KirankumarAmbati** [comment]
@tropicalchancer Need your help.

**Comment by tropicalchancer** [comment]
Hey @KirankumarAmbati - 

We've already talked, I looked into it and not sure why it's happening. Others aren't having the issue. I recommend either reaching out to waffle or using something different.
