### ISSUE TITLE
Inactive/busy Team member

### ISSUE THREAD

**Issue by darkula** [Chingu-cohorts/voyage-wiki#156]
**_About You_**
- Team Name: Geckos team 33
- Slack Name: Adamovics Oskars
- Timezone: UTC+3

**_Issue Description & Expected Outcome:_** One member faridganbarli has been inactive due exam time in school. We were a group of 2 but now I am alone. The fastest time he can join is 19 June

**_Symptoms:_**He has been inactive in the group but response when try to contact with him

**_Steps to Recreate:_** 

**_Resolution:_** Please assign another member in his place if possible.

**Comment by tropicalchancer** [comment]
Message with new team possibility in slack! 🌮
