### ISSUE TITLE
Inactive Team members

### ISSUE THREAD

**Issue by this-mkhy** [Chingu-cohorts/voyage-wiki#157]
**_About You_**
- Team Name: geckos-team-25
- Slack Name: mkhy7
- Timezone: UTC +2

**_Issue Description & Expected Outcome:_**  We were a group of 3. But two member Assi and babalola I don't know anything about them. Assi has been inactive from around more than 6 days. And babalola has not been active for more than 2 weeks

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**  Please assign another members in their place if possible or I like to be on another team

**Comment by tropicalchancer** [comment]
Message sent in slack with new team possibility (worth noting, in the first week Assi made a ticket saying your team was inactive - might be why he isn't active now? )
