### ISSUE TITLE
Inactive Team Member

### ISSUE THREAD

**Issue by foxchristian** [Chingu-cohorts/voyage-wiki#158]
**_About You_**
- Team Name: geckos-team-29
- Slack Name: foxchristian
- Timezone: UTC +00.00

**_Issue Description & Expected Outcome:_** 
Inactive team member since formation of teams (over 2 weeks) - erolaliyev

**_Symptoms:_**
Remaining 2 members of team wish to continue with project with new member

**_Steps to Recreate:_** 

**_Resolution:_** 
assign new member to team.

**Comment by tropicalchancer** [comment]
Message with possible fix sent in slack! 🌮
