### ISSUE TITLE
Not added to Github repo

### ISSUE THREAD

**Issue by zealousAnemone** [Chingu-cohorts/voyage-wiki#159]
**_About You_**
- Team Name: Gecko 03
- Slack Name: Veronica
- Timezone: EST

**_Issue Description & Expected Outcome:_** 
I have not been added to our Github repo/Gotten an invite

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
I @zealousAnemone - I just checked and it's the latter, there must be something going on with the email on your end (invite has been pending since invites were first went week or two ago).

**Comment by tropicalchancer** [comment]
Sent you a link that should fix the issue :)
