### ISSUE TITLE
Inactive team/teammates 

### ISSUE THREAD

**Issue by TyreKing** [Chingu-cohorts/voyage-wiki#160]
Tyre king
- Team Name: geckos-team-2
- Slack Name: Tyre
- Timezone: UTC/GMT -4

**_Issue Description: 
The team that I am placed in does not communicate. I will would like to work on something with people, but I can’t do that if no one is communicating.

Expected Outcome:_**
 being placed into a new team, or add members to the team that are willing to work on something.

**Comment by tropicalchancer** [comment]
Sent a message in slack with possible solution
