### ISSUE TITLE
Switched Teams. Need access to new Team's Repo

### ISSUE THREAD

**Issue by imchetanyadav** [Chingu-cohorts/voyage-wiki#161]
**_About You_**
- Team Name: geckos-team-40
- Slack Name: chetan yadav
- Timezone: GMT + 5:30

**_Issue Description & Expected Outcome:_** 
I was part of geckos-team-36 but switched to geckos-team-40. Need access to geckos-team-40 repo.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Thanks @imchetanyadav Please see here or email for invite https://github.com/chingu-voyage5 🎉
