### ISSUE TITLE
Switched Teams. Need access to new Team's Repo

### ISSUE THREAD

**Issue by darkula** [Chingu-cohorts/voyage-wiki#162]
**_About You_**
- Team Name: geckos-team-33
- Slack Name: Oskars Adamovics
- Timezone: UTC+3

**_Issue Description & Expected Outcome:_** I was part of geckos-team-33 but switched to geckos-team-29. I Need access to geckos-team-29 repo. Also please add access to mkhy7 because he also joined to geckos-team-29

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Thanks @darkula! Done! 🎉 See email or here for invite https://github.com/chingu-voyage5

**Comment by tropicalchancer** [comment]
Please let @mkhy7 know too :)
