### ISSUE TITLE
Switched Team. Need access to new Team's Repo

### ISSUE THREAD

**Issue by Zappy555** [Chingu-cohorts/voyage-wiki#163]
**_About You_**
- Team Name: Toucans-team-21
- Slack Name:  Zandas512
- Timezone: GMT +1

**_Issue Description & Expected Outcome:_** 
My first team mate was inactive and I had to be placed on a new team - team-21.
Now I need access to new teams GitHub's repo for project collaboration
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Done 🎉 See here to accept invite https://github.com/chingu-voyage5
