### ISSUE TITLE
Merging Teams

### ISSUE THREAD

**Issue by ghost** [Chingu-cohorts/voyage-wiki#165]
Team Name: bears-team-28
Slack Name: slioweng
Timezone: GMT+8

The other two team members are involved in another team (#geckos-team-41) and we think it is a good idea to merge the teams (geckos-team-41 will be a group of 4 including myself).

**Comment by tropicalchancer** [comment]
Done! you can find your invite in your email or here --> https://github.com/chingu-voyage5 🎉
