### ISSUE TITLE
Leaving Voyage-5

### ISSUE THREAD

**Issue by Villian79** [Chingu-cohorts/voyage-wiki#166]
**_About You_**
- Team Name: Bears-Team-31
- Slack Name: Villian79
- Timezone: UTC-8

**_Issue Description & Expected Outcome:_** 
Unfortunately, due to personal issues, I won't be able to continue with the voyage.  I ask you to remove me from my team. Hopefully, you will find another voyage member to join the team. Thanks in advance.

**Comment by tropicalchancer** [comment]
@Villian79 please inform your team-mates.

**Comment by Villian79** [comment]
Already informed...
