### ISSUE TITLE
Cannot find github repo invite

### ISSUE THREAD

**Issue by luapuhpuh** [Chingu-cohorts/voyage-wiki#167]
**_About You_**
- Team Name: Ania
- Slack Name: Ania
- Timezone: +2:00

**_Issue Description & Expected Outcome:_** 
I can't find the github repo invite, please help:)
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @luapuhpuh! We actually just found a trick for this: https://github.com/chingu-voyage5
