### ISSUE TITLE
Not sure to be invited to the repo or not 

### ISSUE THREAD

**Issue by ghost** [Chingu-cohorts/voyage-wiki#173]
**_About You_** geckos-team-45 member
- Team Name: geckos-45
- Slack Name: Akbar
- Timezone: UTC+9

**_Issue Description & Expected Outcome:_** 
Wanna be invited (again)
**_Symptoms:_**
Not invited yet or lost the email 
**_Steps to Recreate:_** 
Wanna be invited 
**_Resolution:_** 
I don’t know much to get invited to someone else’s git repo. So I want some instructions what to do in that repo.

**Comment by tropicalchancer** [comment]
https://github.com/chingu-voyage5

Sent you an message in Slack! 🎉
