### ISSUE TITLE
Merge teams

### ISSUE THREAD

**Issue by Anshul2166** [Chingu-cohorts/voyage-wiki#174]
**_About You_**
- Team Name: Bears Team 25
- Slack Name: Anshul
- Timezone: UTC+5.30

**_Issue Description & Expected Outcome:_** Our team and geckos-team-24 have decided to merge our teams.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**  Can you add Amedeo and SpaghettiThots of geckos-team-24 to our repo. Thanks for your help Chance.

**Comment by tropicalchancer** [comment]
Done!
