### ISSUE TITLE
Request for another team

### ISSUE THREAD

**Issue by yapanss** [Chingu-cohorts/voyage-wiki#175]
**_About You_**
- Team Name: Gecko-team-25
- Slack Name: Assi
- Timezone: UTC + 0

**_Issue Description & Expected Outcome:_** 
Want to join a new team 
**_Symptoms:_**
My teammates have left. 
**_Steps to Recreate:_** 

**_Resolution:_** 
Merge me in another team

**Comment by tropicalchancer** [comment]
Sent a DM with a possible solution 🎉
