### ISSUE TITLE
Inactive member

### ISSUE THREAD

**Issue by hash004** [Chingu-cohorts/voyage-wiki#178]
**_About You_**
- Voyage number (5 or 6):  5
- Team Name: Geckos team 44
- Slack Name: hash004 (Hash Brown)
- Timezone: UTC +9

**_Issue Description & Expected Outcome:_** 
One team member has become inactive. Not online on Slack or Discord. We've DM'ed him but no replies. Slack username of member is Art Lavrinovich

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Reached out with info to get a hold of Art and agreed on solution if he doesn't get back
