### ISSUE TITLE
unactive team

### ISSUE THREAD

**Issue by kate-stoner** [Chingu-cohorts/voyage-wiki#179]
**_About You_**
- Voyage number (5 or 6): **5**
- Team Name: **Toucans-09** 
- Slack Name: **Kate Stoner** 
- Timezone: **PST**

**_Issue Description & Expected Outcome:_** 
Both team members are not active, I tried 3 times to set up the time to discuss the future Project and got no response after 3 weeks!  So far we have not started doing anything yet. 
I believe that best solution for me is to leave the team (or maybe close our team at all). 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Sent a DM with a possible solution 🎉
