### ISSUE TITLE
Havent received invite to the team

### ISSUE THREAD

**Issue by blesschews** [Chingu-cohorts/voyage-wiki#18]
I am not added to any team. I have registeredd on chingu.io

**Comment by jdmedlock** [comment]
You are showing as a member in Slack and and your GitHub invitation went out about an hour ago and is waiting on you to click the link in the email. I do not see you in the Geckos 36 Slack channel though. 

Researching...

**Comment by the-vampiire** [comment]
added to team in database. set as PM according to spreadsheet
