### ISSUE TITLE
New Teammate (Voyage-5)

### ISSUE THREAD

**Issue by mels065** [Chingu-cohorts/voyage-wiki#182]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Bears
- Slack Name: mellusbrandon
- Timezone: Eastern Standard Time

**_Issue Description & Expected Outcome:_** 
Our teammate Ashleigh is stepping down and we need a new teammate ASAP

**Comment by tropicalchancer** [comment]
Sent DM with possible solution in slack
