### ISSUE TITLE
One team member is not actively active

### ISSUE THREAD

**Issue by Huongg** [Chingu-cohorts/voyage-wiki#183]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Geckos-team-05
- Slack Name: Huongg
- Timezone: UTC +1

**_Issue Description & Expected Outcome:_one of our team member is not actively involved in the team process. We only 2 members in the team working on the project now. If there's anyone is interested in doing some front-end challenges (HTML/CSS/Javascript is required, better if the person knows about API request or React), please feel welcome to add into our team. We're doing a cool project. 
If you can't find anyone, please let me know as soon as you can please, so we know what we need to do. 

Thanks

**Comment by tropicalchancer** [comment]
Sent a message in slack with a possible solution
