### ISSUE TITLE
Leaving for this Voyage: Toucans-Team-13 (Voyage-5)

### ISSUE THREAD

**Issue by dirkduplooy** [Chingu-cohorts/voyage-wiki#185]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Toucans-Team-13
- Slack Name: dirkduplooy
- Timezone: UCT+2

**_Issue Description & Expected Outcome:_** 
Hi Chance, I think I need to drop out from this voyage, I made the mistake of telling my teammates I was on a previous voyage and that skewed everything, plus I do not know if I am going to make it in terms of JavaScript and web development as a whole, I am in a deep slump. 
**_Symptoms:_**
Demotivated, in despair, teammates expect you to do and know everything
**_Steps to Recreate:_** 

**_Resolution:_** 
Please excuse me for this Voyage, or move me into Voyage 6 as an unknown, not from a previous voyage and not as a project manager

**Comment by tropicalchancer** [comment]
Reached out to the other two members
