### ISSUE TITLE
New Member Needs Repo Access: Geckos-Team-05 (Voyage-5)

### ISSUE THREAD

**Issue by fancyaction** [Chingu-cohorts/voyage-wiki#186]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Geckos-Team-05
- Slack Name: fancyaction
- Timezone: UTC-6

**_Issue Description & Expected Outcome:_**  Add [Slack name] Jethro Fredericks (GitHub: JethroF22) to Geckos-Team-05 GitHub.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
It appears you've changed your repo name as Geckos-team-05 does not show up when I search it.

**Comment by tropicalchancer** [comment]
Can you let me know the repo name? 🙏

**Comment by tropicalchancer** [comment]
Added!
