### ISSUE TITLE
Unable to continue with Voyage-5 

### ISSUE THREAD

**Issue by JamesRileydev** [Chingu-cohorts/voyage-wiki#187]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Geckos-Team-11
- Slack Name: Jim Riley
- Timezone: EST

**_Issue Description & Expected Outcome:_** 
Due to time constraints I'm not able to be fully dedicated to the Voyage so I would like to be removed.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Reached out to @Miguel to make sure the team is all right.
