### ISSUE TITLE
Need a new team member (Voyage-5)

### ISSUE THREAD

**Issue by ghrahul** [Chingu-cohorts/voyage-wiki#188]
**_Rahul Ghosh_**
- Voyage number (5 or 6): 5
- Team Name: bears team 26
- Slack Name: ghrahul98
- Timezone: India

**_Issue Description & Expected Outcome:_** One member is leaving. We need a new member who can work with web app.

**_Symptoms:_**eg

**_Steps to Recreate:_**

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Sent DM in slack
