### ISSUE TITLE
Member inactive

### ISSUE THREAD

**Issue by sigsant** [Chingu-cohorts/voyage-wiki#189]
**_About You_**
- Voyage number (5 or 6):  6
- Team Name: toucans team 09
- Slack Name:  Heros
- Timezone:  UCT +1

**_Issue Description & Expected Outcome:_** 

My team member (we are two person in the team) doesn't show up yet.   Should do I join another team or wait for another team mate?

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Message sent in Slack! 🎉
