### ISSUE TITLE
2 of team members unresponsive

### ISSUE THREAD

**Issue by Vukasinn** [Chingu-cohorts/voyage-wiki#19]
Since the teams have been created only one member has been actively responding. One member who goes by the name Manu Corsica on slack hasn't been online and thus he hasn't answered. Vannya personally emailed him, and he hasn't answered. Then there is slowdata(that's his name on slack).  For 2 days he hasn't answered anything. Only one member as I said was active. Please help.

**Comment by tropicalchancer** [comment]
@manu corsica has been removed from the team. Slowdata has become active. 😀

**Comment by tropicalchancer** [comment]
@Vukasinn if this changes please feel free to make another ticket.
