### ISSUE TITLE
Lost team member (Voyage-5)

### ISSUE THREAD

**Issue by bennythejudge** [Chingu-cohorts/voyage-wiki#190]
**_About You_**
- Voyage number (5): 
- Team Name: geckos-team-22
- Slack Name:  @Tuzzy08
- Timezone:  BST

**_Issue Description & Expected Outcome:_** 
This member has never been active

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 

Please remove from the chat room for out team.

@Wryhder and myself are working on a project.
Thanks

**Comment by tropicalchancer** [comment]
Tuzzy has been removed! 🌮
