### ISSUE TITLE
Member not replying since 4 days

### ISSUE THREAD

**Issue by gabantonelli** [Chingu-cohorts/voyage-wiki#191]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: toucans-team-14
- Slack Name: GabrielAntonelly
- Timezone: GMT+2

**_Issue Description & Expected Outcome:_** 
We are a team of three but we are a bit stuck waiting for a guy to reply and give his contribution.
 We didn't want to go on, define the team leader, decide de project and continue without him but he hasn't been replying for 4 days now. His Slack name is HAMDIKAA.
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
Maybe you have some other people who are left alone on their teams, and might want to join us?
Thanks

**Comment by tropicalchancer** [comment]
Sent a message in slack! 🎉
