### ISSUE TITLE
I can't create any branches on our repository

### ISSUE THREAD

**Issue by sigsant** [Chingu-cohorts/voyage-wiki#192]
**_About You_**
- Voyage number (5 or 6):  6
- Team Name:  Toucans Team 04
- Slack Name: Heros
- Timezone:  UCT + 1

**_Issue Description & Expected Outcome:_** 

I don't have any privilege to create any branch in https://github.com/chingu-voyage6/toucans-team-04.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
You've been invited to the repo now. If you don't see the email invite you should be able to access it by going here --> https://github.com/chingu-voyage6
