### ISSUE TITLE
Inactive Team member

### ISSUE THREAD

**Issue by JethroF22** [Chingu-cohorts/voyage-wiki#193]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Bears-team-21
- Slack Name: Jethro Fredericks
- Timezone: UTC-2

**_Issue Description & Expected Outcome:_** 
One of my team members has been inactive for over a week. He has not responded to messages in the group's channel, nor has he responded to direct messages. He has not contributed to the team's repo either

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
I have already joined a new team, so the remaining team member (Slack username: Aruj Joshi) should be assigned to a new team if he so desires

**Comment by tropicalchancer** [comment]
Sent Aruj a message in slack
