### ISSUE TITLE
Withdrawal from voyage

### ISSUE THREAD

**Issue by cj-hopkins** [Chingu-cohorts/voyage-wiki#194]
**_About You_**
- Voyage number (6): 
- Team Name: bears-team-09
- Slack Name: @conor
- Timezone: UTC

**_Issue Description & Expected Outcome:_** 
I've had a change in personal circumstances that mean I won't be able to continue with the voyage. I hope you can find someone else to be assigned to the team. For what it's worth, I'm sorry to be letting the team down. Under different circumstances I would love to have had completed the voyage, and I really hope I get the oppotunity to take part in another at some time.
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
Assign a new team member to bears-team-09

**Comment by tropicalchancer** [comment]
Hi @abigreenlizard, 

Please let your team know and let them know if they would like to request a new member to make a ticket and I'll try my best to find someone.
