### ISSUE TITLE
Request for new teammates 

### ISSUE THREAD

**Issue by abkr08** [Chingu-cohorts/voyage-wiki#195]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Toucans 20
- Slack Name: Gotzil 
- Timezone: GMT + 3

**_Issue Description & Expected Outcome:_** 
Both teammates inactive. Requesting for a new team. 
**_Symptoms:_**
Both teammates not responding to messages 
**_Steps to Recreate:_** 

**_Resolution:_** 
I hope I can be placed in a team of enthusiastic and active teammates

**Comment by tropicalchancer** [comment]
Added! 🎉
