### ISSUE TITLE
Transfer team-repo between organizations

### ISSUE THREAD

**Issue by mar-bi** [Chingu-cohorts/voyage-wiki#196]
**_About You_**
- Voyage number (5 or 6): **6** 
- Team Name: **bears-01**
- Slack Name: **mar-bi**
- Timezone: **GMT+ 2**

**_Issue Description & Expected Outcome:_** 
I would like to transfer our team repo from *chingu-voyage4* (https://github.com/chingu-voyage4/grad.then) to current *chingu-voyage6*.
**_Symptoms:_**
It seems, I can't do it by myself, because the repo transfer involves **permissions** set by the organization. In *voyage6* I'm not even in a team for our repo on github. (I haven't got an invitation).
**_Steps to Recreate:_** 

**_Resolution:_** 
I wish, you can help me with the transfer :upside_down_face: :
- from https://github.com/chingu-voyage4/grad.then
- to https://github.com/chingu-voyage6/Bears-Team-01

Thanks

**Comment by tropicalchancer** [comment]
Hi @mar-bi! 

I sincerely apologize for that 🙏 It's been transferred and you and @miljan-fsd have been added!
