### ISSUE TITLE
Add a teammate

### ISSUE THREAD

**Issue by hafsasam** [Chingu-cohorts/voyage-wiki#198]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name:  geckos-team-34
- Slack Name:  @sam
- Timezone: UTC

**_Issue Description & Expected Outcome:_** 

**_Symptoms:_**
Found a member that can join our team ,and that is @Gotzil 
**_Steps to Recreate:_** 

**_Resolution:_** 
Add @Gotzil to geckos-team-34

**Comment by tropicalchancer** [comment]
Added 🎉
