### ISSUE TITLE
Need a new team member

### ISSUE THREAD

**Issue by SnGrimes** [Chingu-cohorts/voyage-wiki#199]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Geckos-Team-14
- Slack Name: SnGrimes
- Timezone: CST

**_Issue Description & Expected Outcome:_** 
One of our team members will be unable to continue with the voyage due to time constraints. That leaves us with 2 people and would like a new team member.

**Comment by debasree888** [comment]
I can work. My teammates( geckos-06) have stopped responding for 5 days. I can work for 15-20 hours a week. 
my slack username: Debasree Tenyson
my timezone: IST

**Comment by tropicalchancer** [comment]
Sent a message in slack with a possible solution 🎉
