### ISSUE TITLE
Add trello + waffle examples url to tasks section

### ISSUE THREAD

**Issue by tropicalchancer** [Chingu-cohorts/voyage-wiki#2]
**_Issue Description & Expected Outcome:_** 
Add trello URL to tasks section so people have an example of what each look like in action.

**Comment by jdmedlock** [comment]
Added an **_Additional Resources_** list to the end of Section 03. Defining Your Team. Added links to GitHub Projects, Trello, and Waffle.io.

**Comment by sfiquet** [comment]
There is problem with the links: They all have the format https://github.com/Chingu-cohorts/voyage-wiki/wiki/url so when I click on them I end up on the wiki home page.
e.g. for Trello the link is https://github.com/Chingu-cohorts/voyage-wiki/wiki/www.trello.com
