### ISSUE TITLE
@ruxi from geckos-33 has to leave 

### ISSUE THREAD

**Issue by tropicalchancer** [Chingu-cohorts/voyage-wiki#20]
@ruxi from geckos-33 has to leave

**Comment by jdmedlock** [comment]
To be addressed on Team Repair Day - 2/22/2018

**Comment by jdmedlock** [comment]
From #wizard-issues: 

Fou [3:15 PM]
Hi guys. I think our PM bailed. I can't get hold of her and she closed out Trello board. I guess that means she's out. We're geckos-team-33

**Comment by jdmedlock** [comment]
![image](https://user-images.githubusercontent.com/1287072/36398180-7325c72e-158b-11e8-97c6-445d5c5268e6.png)

**Comment by tropicalchancer** [comment]
Team is closed down. 

@fou has been moved to Geckos-10. 
@cooke has not been active or contributed, so shall be removed. 
@heyjp is already in another project, but he has been contacted to see if he'd like to join another project still, at which point we'll find him a new home. 🚀
