### ISSUE TITLE
A team member cannot access our repo

### ISSUE THREAD

**Issue by AlexGherardelli** [Chingu-cohorts/voyage-wiki#200]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Bears-18
- Slack Name: @gherds
- Timezone: GTM+2

**_Issue Description & Expected Outcome:_** 
My team mate @sfiquet (@sylvie on Slack) can't access our repository (https://github.com/chingu-voyage4/BitHelper/) and I cannot add her as part of the team since I'm not the owner.

The outcome is that she can contribute! Either by moving our repo to Voyage5 or by updating our current team with her

**_Symptoms:_**
She gets an error when trying to push to our repo.

**_Steps to Recreate:_** 
She's not listed in the contributors&teams list (Bears-team-8, which is the team from Voyage4)
https://github.com/chingu-voyage4/BitHelper/ 

**_Resolution:_** 

Get her on the team!

**Comment by tropicalchancer** [comment]
Thanks for making a ticket. I apologize for not having this done before - I juggle too many things and reminders like this are a godsend 🙏

**Comment by tropicalchancer** [comment]
The repo has been transferred and everyone has been sent an invite. Let me know if there are any other issues.
