### ISSUE TITLE
Bears-Team-13: Team members not added as contributors

### ISSUE THREAD

**Issue by smatoto** [Chingu-cohorts/voyage-wiki#201]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Bears-Team-13
- Slack Name: sermil
- Timezone: SGT

**_Issue Description & Expected Outcome:_** 
Our team is unable to access the repo provided for the voyage: https://github.com/chingu-voyage6/Bears-Team-13

**_Symptoms:_**
We can pull but can't push to the repository.
**_Steps to Recreate:_** 
We are not listed as contributors on the repository.
**_Resolution:_** 
Add us as contributors on the repository. Please refer to the GitHub usernames below for team members that needs to be added:
@ievgenk
@smatoto
@ikanyu

**Comment by tropicalchancer** [comment]
Thanks for making a ticket @smatoto. 

I checked your situation and everything looks to be as it should be from our end. You've all accepted your invite, are all in, and have "admin" access to the repo. 

When code is pushed to the repo it'll show whoever pushed it as a contributor to the repo. 

I'll send you a slack message to chat further.
