### ISSUE TITLE
Team Change

### ISSUE THREAD

**Issue by niamurrell** [Chingu-cohorts/voyage-wiki#202]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Bears team 9
- Slack Name: nia
- Timezone: UTC +1

**_Issue Description & Expected Outcome:_** 
After some changes in our original team, please can you move me to Geckos team 5 with push/pull access to their Github repo and team member access to the team's Slack channel. Thanks!

Bears team 9 repo can be deleted.

**Comment by tropicalchancer** [comment]
Added 🎉
