### ISSUE TITLE
Team Member is inactive

### ISSUE THREAD

**Issue by nickeyvee** [Chingu-cohorts/voyage-wiki#203]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Geckos-Team-10
- Slack Name: nickey_vee
- Timezone: Eastern Standard Time (New York)

**_Issue Description & Expected Outcome:_** 
One of our team members has been inactive for 3 days and we would like them removed. They are not making themselves available and we would like to move forward to Act 2.

**_Resolution:_** 
Replace the inactive team member with someone else to help us take on the project.

**Comment by tropicalchancer** [comment]
Set up possible solution in slack. If it doesn't workout please make another ticket and we'll look for another match 🙏
