### ISSUE TITLE
permissions for making a slackbot

### ISSUE THREAD

**Issue by mepda** [Chingu-cohorts/voyage-wiki#204]
**_About You_**
- Voyage number (5 or 6): 
- Team Name: Geckos 43
- Slack Name: lePancake
- Timezone: Seoul

**_Issue Description & Expected Outcome:_** 
I'd like permission to add a slackbot to general that tells the pollutions when deployed
**_Symptoms:_**
n/a
**_Steps to Recreate:_** 
n/a
**_Resolution:_** 
get a slack bot token and then setup the bot I made so that I can test it in a real environment (not just in a playground slack)

**Comment by tropicalchancer** [comment]
Sent you a slack DM @mepda
