### ISSUE TITLE
Inactive Team member

### ISSUE THREAD

**Issue by Eleutherado** [Chingu-cohorts/voyage-wiki#205]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Bears Team 4
- Slack Name: Emilio Vv
- Timezone: GMT -4 

**_Issue Description & Expected Outcome:_** 
We have an inactive teammate and it has been more than 3 days since they have answered any messages. We would prefer if we can get another teammate. 

**_Resolution:_** 
If possible, Replace the inactive team member with someone else to help us take on the project. This might be a reach, but if they have design skills then that is ideal

**Comment by debasree888** [comment]
I am willing to work. I have not heard from my team(geckos-06) members for 5 days. I can work for 15 to 20 hours a week. 
my timezone: utc+ 5:30

**Comment by tropicalchancer** [comment]
@Eleutherado sent a message in slack with a possible solution 🎉
