### ISSUE TITLE
just changed teams - need a github invite

### ISSUE THREAD

**Issue by luapuhpuh** [Chingu-cohorts/voyage-wiki#206]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Toucans 21
- Slack Name: Ania Nnk
- Timezone: +0,2UTC

**_Issue Description & Expected Outcome:_** 
I have moved teams a few days ago and forgot to ask for a new github repo invite, please send me one if possible, thank you!
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
You've been added to Toucans 21 @luapuhpuh :) 

You can find your invite by going here --> https://github.com/chingu-voyage5
