### ISSUE TITLE
How to access Slack archived messages

### ISSUE THREAD

**Issue by simonxcode** [Chingu-cohorts/voyage-wiki#207]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Gecko
- Slack Name: Gecko-Team-16
- Timezone: PST

**_Issue Description & Expected Outcome:_** 

How do I access archived chat history on slack? Did a search and was only given instructions on how to archived not actually "view" archived. 

Thanks!

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by mepda** [comment]
This slack is a freebie, so I think we only have access to the most recent 10,000 messages. You won't be able to access messages before that unless they were pinned.

**Comment by simonxcode** [comment]
Not sure what happened to the "archived" message on my team's channel but it has been removed, so problem have been fixed or disappeared. Thank you for the explanation and your help.
