### ISSUE TITLE
Github Invitation

### ISSUE THREAD

**Issue by shotenxz** [Chingu-cohorts/voyage-wiki#208]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Geckos-Team-14
- Slack Name: Alberto
- Timezone: UTC -5

**_Issue Description & Expected Outcome:_** 
I have moved teams a few days ago and forgot to ask for a new github repo invite, please send me one if possible, thank you!
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
@shotenxz you've been added 🎉
