### ISSUE TITLE
Searching for new team member

### ISSUE THREAD

**Issue by mvoltairec** [Chingu-cohorts/voyage-wiki#209]
**_About You_**
- Voyage number (5 or 6): Voyage 5
- Team Name: Bears 5
- Slack Name: mvoltairec
- Timezone: UTC -5

**_Issue Description & Expected Outcome:_** 
We were a team of 4. One team member had to withdraw and another team member has less hours he can commit due to a new work schedule. Looking for someone who is willing and able to dedicate a minimum of 10-15 hours a week to complete MVP by July 20th. I've already asked on slack and have a few people who are responding - however they are 6 + hours ahead of us, so not completely sure if they can work with our team! 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by armatis** [comment]
I'm willing to join. I haven't heard a word from my team (geckos-team-15) and I'm not really sure what to do. I can devote 10-15 hours per week and currently work as a JS dev full-time, so my skills are pretty versatile.

My time zone is UTC -7.

Dan

**Comment by tropicalchancer** [comment]
Looks like a good fit to me! 🎉 @armatis @mvoltairec
