### ISSUE TITLE
@lyatar from geckos-13 has had to leave

### ISSUE THREAD

**Issue by sipofwater** [Chingu-cohorts/voyage-wiki#21]
@lyatar from geckos-13 has had to leave due to time commitments/new job

**Comment by jdmedlock** [comment]
Reassigned to be addressed during this weeks team repair activities.

**Comment by tropicalchancer** [comment]
Sent Jake a message and once he replies we'll determine if the team is fit to go on as 3 or look for another solution.

**Comment by tropicalchancer** [comment]
We'll add a new member is a free-agent appears. Until then we'll consider this ticket closed and will keep in touch with Jake to monitor the situation.
