### ISSUE TITLE
 put me in another team as team members stopped responding 

### ISSUE THREAD

**Issue by debasree888** [Chingu-cohorts/voyage-wiki#210]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: geckos-6
- Slack Name: Debasree Tenyson
- Timezone:UTC + 5:30

**_Issue Description & Expected Outcome:_**  Team members are extremely inactive. They hardly respond. I have not heard anything from them for 5 days despite my several messages. So it mars team progress. 
I want to join another team. Please

**_Symptoms:_**
   Team members have stopped responding for 5 days. Team can not be progressed. The works that I could have easily finished by now, are still hanging in midway incomplete due to them.
**_Steps to Recreate:_** 
 My another friend yesterday told me that they need another team member. So I am willing to join.
his slack username: abhi-hk95
**_Resolution:_** 
 Please merge me in another team.

**Comment by rhouari** [comment]
please put me in another team. I find one of the team member to be quite tense and I prefer to learn in a more friendly atmosphere. @rhouari
