### ISSUE TITLE
Joining Bear Teams 12

### ISSUE THREAD

**Issue by psongpin** [Chingu-cohorts/voyage-wiki#211]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Bears Team 30
- Slack Name: #bears-team-30
- Timezone: GMT/UTC +8

**_Issue Description & Expected Outcome:_** 
Joining Bears-Team-12. Temporarily take a break from Bear-Team-30. 

**_Symptoms:_**
I feel like being left out because for some reason I can't join in video calls as I am only working with mobile data. Also I feel like not being part of the decision making process. Maybe it was just a miscommunication but things became harder to resolve especially when I introduced a good workflow yet they where hesitant to accept change. 

**_Resolution:_** 
Please let me join Bears-Team-12 I have already talked with them personally. But please don't remove me from Bear-Team-30. I might help them build something or do code reviews.

**Comment by tropicalchancer** [comment]
Added! 🎉
