### ISSUE TITLE
Need a new Team

### ISSUE THREAD

**Issue by ps290513** [Chingu-cohorts/voyage-wiki#212]
i am priyanka from india currently situated in Uk. I have   
- Voyage number (5 or 6): Voyage 6
- Team Name: Tucans-team-20 
- Slack Name: Chingu Voyage 6
- Timezone: UTC +1

I need a new team. As my current team is already split. :(

**Comment by tropicalchancer** [comment]
Message sent in slack with possible solution! 🙏
