### ISSUE TITLE
Need to quit voyage

### ISSUE THREAD

**Issue by zealousAnemone** [Chingu-cohorts/voyage-wiki#213]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Geckos 3
- Slack Name: Veronica
- Timezone: EST

**_Issue Description & Expected Outcome:_** 
We have had some life issues come up that are impeding my ability to be a good teammate and participate fully in this voyage right now. I am going to have to quit for this voyage, and ask that you find another team member for my team if possible and if they want one.

I hope to be able to participate in a future voyage once life settles down again....

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @zealousAnemone, I'm sorry to hear that and I hope everything is all right. 🙏 

I'll reach out to your team to see, thanks.
