### ISSUE TITLE
Need Github Invitation

### ISSUE THREAD

**Issue by debasree888** [Chingu-cohorts/voyage-wiki#214]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Geckos-10
- Slack Name: Debasree Tenyson
- Timezone: IST

**_Issue Description & Expected Outcome:_** 
Joined this new team. So need an invitation to be able to commit to this team repository.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Added! 🎉
