### ISSUE TITLE
I need to quit the voyage

### ISSUE THREAD

**Issue by rmorabia** [Chingu-cohorts/voyage-wiki#215]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: bears-team-02
- Slack Name: bears-time-02
- Timezone: EST

**_Issue Description & Expected Outcome:_** 

I just got a job (!!!), so I understandably need to drop out of the voyage to focus on this now. I've already told & warned my teammates as this was happening. If you can, please replace me with someone else. Thanks, Chance.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Wow, congratulations @rmorabia! 

Can you please let your team know that if they want to request another person to make a ticket here please 🙏
