### ISSUE TITLE
Need a new teammate

### ISSUE THREAD

**Issue by Ablakes** [Chingu-cohorts/voyage-wiki#216]
**_About You_**
- Voyage number (5 or 6): **6**
- Team Name: **Geckos Team 16**
- Slack Name: **@ablakes**
- Timezone: **UTC-7**

**_Issue Description & Expected Outcome:_** 

We haven't heard from our teammate @tupo for over a week. We'd like a new teammate or two as people become available, please :)

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by davidlondonor** [comment]
About You

Voyage number (5 or 6): 4
Team Name: Toucans 18
Slack Name: @DavidL
Timezone: (UTC -5) 
Issue Description & Expected Outcome:

we do not know anything about the other partners.
We are only active two in the @jesica group and me
