### ISSUE TITLE
Switch Team Leaders

### ISSUE THREAD

**Issue by beboptank** [Chingu-cohorts/voyage-wiki#217]
**_About You_**
- Voyage number (5 or 6): 5 
- Team Name: Geckos-44
- Slack Name: beboptank
- Timezone: UTC +9

**_Issue Description & Expected Outcome:_** 

Current team leader wishes to transfer those duties and responsibilities to me due to schedule and time constraints. I would need to be added to the team lead Slack channel.

**_Symptoms:_**
N/A
**_Steps to Recreate:_** 
N/A
**_Resolution:_** 
Transfer team lead title from current team lead to myself, get added to team lead Slack channel. Thank you!

**Comment by tropicalchancer** [comment]
Added! 🎉
