### ISSUE TITLE
Not added to team's github repo

### ISSUE THREAD

**Issue by jeffersonnnn** [Chingu-cohorts/voyage-wiki#22]
**_Issue Description & Expected Outcome:_** 
Hi guys, amazing work with this community. One issue though, i did not recieve the mail from chance with the invite to my teams github repo
**_Symptoms:_**
My team is Toucan team 2, my mail is jefferie.halo@gmail.com and my slack handle is jeff
**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @jeffersonnnn, looking into it now 💯

**Comment by tropicalchancer** [comment]
I apologize for my mistake @jeffersonnnn! You've been added. Please check your email (including spam folder if you don't see it in your main email). 

Cheers!! 🚀

**Comment by jeffersonnnn** [comment]
thank you, chance!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
