### ISSUE TITLE
Looking for new team member with MERN experience

### ISSUE THREAD

**Issue by xChristianZx** [Chingu-cohorts/voyage-wiki#220]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Bears-team-02
- Slack Name: christianz
- Timezone: -7 UTC (PDT) & -5 UTC (CDT)

**_Issue Description & Expected Outcome:_** 
We are down one team member from Issue #215 and are interested in acquiring a new member / "free agent".

We are building a Full-stack app with MERN (Mongo, Express, React, Node), it is a spin-off of Angelist, called Founder Connect, matching Technical Founders with Non-Technical Founders.  Our ideal MVP is a social networking CRUD app with some bells and whistles.

We are looking for someone ideally with at least intermediate experience with the MERN stack, especially with React and working on the frontend.  Anyone that is comfortable working the full stack would be great as well.

Take a look at our repo below for more info and user stories.
[Our Repo](https://github.com/chingu-voyage6/Bears-Team-02)

I'm not sure of the formality of it all but will ultimately defer the selection process to @tropicalchancer or one of the other moderators.

Please reach out if you have any questions.  Thanks!

**Comment by AdamSackfield** [comment]
I’m up for working on this project. Not sure if it’s allowed though as I am in another team, which I am PM. Although I have adequate time to spend on both projects. Easily 60 hours per week across the two.

**Comment by xChristianZx** [comment]
@AdamSackfield Thanks for the reaching out.  I just noticed @tropicalchancer was updating issues this morning and that the weekly check-in went out so will wait to hear back from him.

**Comment by tropicalchancer** [comment]
Message sent in slack! 🙏
