### ISSUE TITLE
Need new team member

### ISSUE THREAD

**Issue by cjaquino** [Chingu-cohorts/voyage-wiki#222]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Geckos Team 3
- Slack Name: Jerritt
- Timezone: UTC-4

**_Issue Description & Expected Outcome:_** 
We lost a team member due to personal issues. This is the first voyage for both of us remaining so another person would definitely help out, preferably with previous voyage experience.

We're attempting to clone the map section of hikingproject.com

**Comment by tropicalchancer** [comment]
Hey @cjaquino thanks for making a ticket. I'll keep an eye out for a potential team-mate and reach out when I find one. In the mean-time, I encourage you and your team-mate to push ahead to build momentum. 

If I don't see anyone to add by Monday I'll reach out to see what our options are 🙏

**Comment by tropicalchancer** [comment]
Message sent in slack 🙏
