### ISSUE TITLE
Need new teammate with experience with Spring Boot

### ISSUE THREAD

**Issue by mels065** [Chingu-cohorts/voyage-wiki#223]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Bears Team-8
- Slack Name: Mellusbrandon
- Timezone: Eastern Standard Time

**_Issue Description & Expected Outcome:_** 
Our teammate ghrahul98 has been unresponsive the past few weeks. We're looking for another one to replace him, particularly one that is familiar with Spring Boot.

**Comment by tropicalchancer** [comment]
Message sent in slack
