### ISSUE TITLE
Travis CI auth access request.

### ISSUE THREAD

**Issue by Spell2az** [Chingu-cohorts/voyage-wiki#224]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: geckos-team-04
- Slack Name:  Martin Kovac
- Timezone: UTC +1

**_Issue Description & Expected Outcome:_** 
As a part of learning process we're trying to integrate Travis CI into our workflow which requires access to this organisation. Request has been created and approval is pending. 
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
Confirm auth access request for Travis CI

**Comment by tropicalchancer** [comment]
Accepted! 🎉

**Comment by tropicalchancer** [comment]
If there's any further issues please let me know 🙏
