### ISSUE TITLE
Team member needs to be added to Geckos Team 13 Github Organization

### ISSUE THREAD

**Issue by megclaypool** [Chingu-cohorts/voyage-wiki#225]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Geckos Team 13
- Slack Name: megclaypool
- Timezone: Pacific

Hey there,

One of our teammates is not a member of our Github Organization. Since all members of our organization have admin privs for our repo, I was able to add her to the repo as a collaborator. However, I don't have admin privs for the organization itself. We were thinking of using the discussion feature, since the slack channel gets deleted every couple of days, but that won't work if we don't all have access.

Could you please add Katie Young ([tkoya](https://github.com/tkoya)) to our [Geckos Team 13 organization](https://github.com/orgs/chingu-voyage5/teams/geckos-team-13/members)?

Thanks :)

**Comment by tropicalchancer** [comment]
Added! 🎉

**Comment by megclaypool** [comment]
Hmmm... Somehow Katie ([tkoya](https://github.com/tkoya)) is still not a member of [our organization](https://github.com/orgs/chingu-voyage5/teams/geckos-team-13/members). I've tried reloading, but I'm still just seeing 3 members -- you, Waswa, and myself. Can you take a look?
