### ISSUE TITLE
Need a new member for the team

### ISSUE THREAD

**Issue by Sohel-ASM** [Chingu-cohorts/voyage-wiki#227]
**_About Geckos-01**
- Voyage number ( 5 or 6): 6  
- Team Name: Geckos-01 
- Slack Name: Geckos-team-01
- Timezone: EST -5

**_Issue Description & Expected Outcome:_** 
We were originally a 3 members team (other than constant Chance), one member formally dropped off the team yesterday. Another member beside me is a newbie, and most likely joined/placed in an unsuitable tier team for her (btw, Geckos-01 is a Tier-2 team). So can't rely on her much. Given the circumstances, and the project our team selected and choose to work on, we are in need of a new member. Looking for someone with experience or would like to have experience on node.js and mongodb. Otherwise, it would be a difficult workload for me to shoulder on singularly, given the tight schedule I currently have.      
**_Symptoms:_**
The member notified me in our team's primary communication medium (Discord), that for personal reason, she won't be able to carry on further, and is ready to drop out.  
**_Steps to Recreate:_** 
Nothing major needs to recreate now. 
**_Resolution:_** 
Someone with experience on either node.js or mongodb or both technologies, or would like to build skills on those technologies will be graciously welcomed to join in the team.

**Comment by tropicalchancer** [comment]
Message sent in slack 🙏
