### ISSUE TITLE
Permission to be removed from Bears-team-30

### ISSUE THREAD

**Issue by psongpin** [Chingu-cohorts/voyage-wiki#228]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Bears-Team-30
- Slack Name: Bears-Team-30
- Timezone: GMT +8

**_Issue Description & Expected Outcome:_** 
Permission to remove me from bears-team-30. The issue has worsen and I am not in the position to fix the issue. I already said my farewell to them. I am already working with bears-team-12.

**Comment by tropicalchancer** [comment]
Ok thanks for letting me know @psongpin 🙏
