### ISSUE TITLE
Need to add (another) team mate to Geckos-Team-14

### ISSUE THREAD

**Issue by SnGrimes** [Chingu-cohorts/voyage-wiki#229]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Geckos-Team-14
- Slack Name: SnGrimes
- Timezone: CST 

**_Issue Description & Expected Outcome:_** 
@mendyz was recently added to our team and he brought along another voyager that didn't have a team. His slack name is @DraciVik and he is in GMT+2 timezone. I didn't get a response in Slack if that was okay or not. 
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
He just needs to be officially added to the team and the git repo. Can you also confirm that mendyz was added to Geckos-Team-14 github team?

**Comment by tropicalchancer** [comment]
Both @mendyz and @dracivik have been added! (both are pending now) 🎉

**Comment by tropicalchancer** [comment]
Also you might want to reach out to @mendyz as his has been pending for a few days now

**Comment by SnGrimes** [comment]
Thanks Chance. I'll follow-up with Mendyz again because he keeps telling me he hasn't gotten an email.
