### ISSUE TITLE
Can you activate me as a PM?

### ISSUE THREAD

**Issue by lazycesar** [Chingu-cohorts/voyage-wiki#23]
**_Issue Description & Expected Outcome:_** 
Can you activate me as a PM?

Toucans-Team-4

thx

**Comment by tropicalchancer** [comment]
Hi @lazycesar! 

This issue has been reassigned and should be fixed in the next few days. In the mean-time, you can view the roadmap [here](https://github.com/Chingu-cohorts/voyage-wiki/wiki/Voyage-Roadmap)

**Comment by the-vampiire** [comment]
fixed @jdmedlock @tropicalchancer
