### ISSUE TITLE
Need some guidance to complete the work alone.

### ISSUE THREAD

**Issue by adsingh14** [Chingu-cohorts/voyage-wiki#230]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Toucans Team 20
- Slack Name: Aman
- Timezone: UTC +5

**_Issue Description & Expected Outcome:_** From last 2 weeks, I didn't get any update/reply from my team partner. Before 2 weeks, we've divided our work & update it asap.

**_Symptoms:_** 
- I didn't get reply from my partner's side. 

**_Steps to Recreate:_** I think I have to code the remaining part (of my partner's) asap.

**_Resolution:_** All I need is some guidance. Except that, I know how to code alone. But I really didn't want to work without my partner(leader).

**Comment by tropicalchancer** [comment]
Message sent in slack :)
