### ISSUE TITLE
Inactive member

### ISSUE THREAD

**Issue by AFMR** [Chingu-cohorts/voyage-wiki#231]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Toucans 08
- Slack Name: Eury
- Timezone: PST

**_Issue Description & Expected Outcome:_** 
An inactive member in the team (domacles)

**_Symptoms:_**
domacles only answered once the first week, no more communication.
**_Steps to Recreate:_** 
Please remove domacles from the team and if possible we would love to have a new member preferably with experience in WordPress, otherwise we will remain as a 3 members team :)
**_Resolution:_**

**Comment by tropicalchancer** [comment]
Removed @domacles and sent a message in slack 🎉
