### ISSUE TITLE
Inactive member

### ISSUE THREAD

**Issue by jessiepenaloza** [Chingu-cohorts/voyage-wiki#232]
**_About You_**
- Voyage number (5 or 6):  3
- Team Name: Toucans 18
- Slack Name: jesica
- Timezone: -3

**_Issue Description & Expected Outcome:_** 
There is an inactive member 

**_Symptoms:_**
This memeber answered messages only once.

**_Steps to Recreate:_** 
To add a new member so we can be 3 persons working on a project 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Message sent in slack 🎉
