### ISSUE TITLE
Looking for a group to join

### ISSUE THREAD

**Issue by ganto1812** [Chingu-cohorts/voyage-wiki#233]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Toucans 10
- Slack Name: Antonella
- Timezone: UTC +1

**_Issue Description & Expected Outcome:_** 
Both of my teammates have decided to quit.

**_Symptoms:_**
Due to personal reasons both have decided to quit the project.

**_Steps to Recreate:_** 
Add me to another group

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Message sent in slack 🎉
