### ISSUE TITLE
Member missing

### ISSUE THREAD

**Issue by GlynL** [Chingu-cohorts/voyage-wiki#234]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Bears-12
- Slack Name: geelie
- Timezone: +10

**_Issue Description & Expected Outcome:_**  Member missing (down to 2)

**_Symptoms:_**
Member been missing over a week.

**_Steps to Recreate:_**  We are happy to join a new tema or add a member. Otherwise, we will persist with two.

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Message sent in slack 🎉
