### ISSUE TITLE
Inactive Team

### ISSUE THREAD

**Issue by kedanco** [Chingu-cohorts/voyage-wiki#235]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Geckos-41
- Slack Name: Kedanco
- Timezone: GMT +8

**_Issue Description & Expected Outcome:_** 
Team of 4 but Members aren't responding, looking forward to be placed into a new team

**_Symptoms:_**
Members no longer responding on Slack.

**_Steps to Recreate:_** 
NIL

**_Resolution:_** 
Currently learning about the MERN Stack, familiarity with Ruby on Rails, Javascript.
Looking forward to join a team that's ok with my timezone and skillsets.

**Comment by tropicalchancer** [comment]
Message sent in slack 🎉
