### ISSUE TITLE
Member withdraval

### ISSUE THREAD

**Issue by muratmer** [Chingu-cohorts/voyage-wiki#236]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: geckos 22
- Slack Name: muratmer
- Timezone: GMT+3.00

**_Issue Description & Expected Outcome:_** 
One of our member, Alexei had to leave due to family problems.
**_Symptoms:_**

**_Steps to Recreate:_** 
We need a New member or team merge.
**_Resolution:_**

**Comment by tropicalchancer** [comment]
Message sent in slack! 🎉
