### ISSUE TITLE
Need a new member

### ISSUE THREAD

**Issue by JustbeingD** [Chingu-cohorts/voyage-wiki#237]
**_About You_**
- Voyage number (5 or 6): 
- Team Name:  Gecko Team 11
- Slack Name:  Denis
- Timezone: UTC -5

**_Issue Description & Expected Outcome:_** 
Member Withdrawl - Team member Kenito Henry had to leave due to work.
**_Symptoms:_**

**_Steps to Recreate:_** 
Looking for a replacement.
**_Resolution:_**

**Comment by tropicalchancer** [comment]
Message sent in slack! 🎉
