### ISSUE TITLE
Wizzard error

### ISSUE THREAD

**Issue by tasesmuemils** [Chingu-cohorts/voyage-wiki#239]
**_About You_**
- Voyage number (5): 
- Team Name: Toucans 16
- Slack Name: tasesmuemils
- Timezone: +2

I am trying to use Wizard on our team chat but it`s not working.
![image](https://user-images.githubusercontent.com/18176025/42060919-251aea30-7b31-11e8-9b1b-1f4c6b0957a8.png)

**Comment by tropicalchancer** [comment]
Message sent in slack
