### ISSUE TITLE
Need A New Member

### ISSUE THREAD

**Issue by dhairyadwivedi** [Chingu-cohorts/voyage-wiki#242]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Geckos-26
- Slack Name: Dhairya
- Timezone: +5:30

**_Issue Description & Expected Outcome:_** 
One of our team mates has left the team so we require a new team member in order to move forward.
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Message sent in slack 🙏
