### ISSUE TITLE
Would like to merge our team with some other team.

### ISSUE THREAD

**Issue by anuragsachdeva28** [Chingu-cohorts/voyage-wiki#243]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Geckos-Team-35
- Slack Name: webcrawler
- Timezone: GMT+5:30

**_Issue Description & Expected Outcome:_** 
One of our "Abhijit" is not coming active regularly due to which our team has not even started with our project. Until now we should be on our sprints.

**_Symptoms:_**
Consequences are that we are not able to build anything or learn.

**_Steps to Recreate:_** 
I and my other teammate "Faiz" would like to join some other team who have more experienced persons who can help us.
**_Resolution:_**

**Comment by tropicalchancer** [comment]
Message sent in slack 🎉
