### ISSUE TITLE
Leaving voyage 5

### ISSUE THREAD

**Issue by bennythejudge** [Chingu-cohorts/voyage-wiki#244]
**_About You_**
- Voyage number (5): 
- Team Name: Geckos-team-22
- Slack Name: blg
- Timezone: CEST

**_Issue Description & Expected Outcome:_** 
Unfortunately I need to leave the voyage as I have no more time to dedicate to it.
Thanks!

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
@bennythejudge thanks for letting us know. Please let your team-mate(s) know and that if they want to look for a new team to merge with to make a ticket here 🙏
