### ISSUE TITLE
github repo invite please :)

### ISSUE THREAD

**Issue by luapuhpuh** [Chingu-cohorts/voyage-wiki#245]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Toucans 21
- Slack Name: Ania
- Timezone: UTC +2,00

**_Issue Description & Expected Outcome:_** 
Could I please get an invite to my team's github repo ? I have changed teams recently and still haven't recieved one, thank you!

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @luapuhpuh! Thanks for making a ticket. 

I checked and it appears you had been invited to Toucans-21 and the invite is still pending. Is it another team you've joined that is not Toucans-21? 

You can also visit here to accept your invite --> https://github.com/chingu-voyage6
