### ISSUE TITLE
Would like to move to other TEAM

### ISSUE THREAD

**Issue by redmundnacario** [Chingu-cohorts/voyage-wiki#246]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: 25
- Slack Name: redmundnacario
- Timezone: +8 UTC

**_Issue Description & Expected Outcome:_** 

My local friend ,who is also part of Voyage 6, encourage me to join their team due to lack of members in their side. Maybe I could join them because I believe that i will grow more with them as a developer and to finish the voyage 6. 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @redmundnacario - you're free to work with them, as well as your current team. I don't encourage you to switch teams completely unless you can provide a new member for your initial team. 

Please let me know what you decide 🙏
