### ISSUE TITLE
Withdrawal from Voyage 5

### ISSUE THREAD

**Issue by LFoged** [Chingu-cohorts/voyage-wiki#247]
**_About You_**
- Voyage number: 5 
- Team Name: Bears-team-23
- Slack Name: louisf
- Timezone: CEST

**_Issue Description & Expected Outcome:_** 
Working on a business opportunity (potentially starting a company) that will demand my time and focus for the next while. 
Unfortunately, I won't have time for the Voyage, as I have to fully prioritize this opportunity.

Thanks for the great ride so far!
Looking forward to joining another Voyage, further down the line :-) 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Thanks for letting us know @LFoged - please let your team know that if they wish to request a new member or merge with another team to make a ticket. 🙏
