### ISSUE TITLE
Join  / Merge with another team

### ISSUE THREAD

**Issue by LoneWolf36** [Chingu-cohorts/voyage-wiki#248]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Toucans team 23
- Slack Name: Faizan Khan
- Timezone: UTC/GMT +5:30 hours

**_Issue Description & Expected Outcome:_** 
My teammate (1) isn't able to get time out from his job to get work done in our voyage, so didn't actually make a lot of progress and currently I'm hindered.
So I'd like to merge with another team and work with them.
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Message sent in slack 🎉
