### ISSUE TITLE
Voyage 5 withdrawal

### ISSUE THREAD

**Issue by cjaquino** [Chingu-cohorts/voyage-wiki#249]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Geckos 3
- Slack Name: jerritt
- Timezone: utc-4

**_Issue Description & Expected Outcome:_** 
My company landed a pretty big job recently and I thought I would still be able to commit time to Chingu. Unfortunately, this isn't the case and have to focus all my attention to my job.

I'm hoping to sign up for another voyage in the near future when we finish 
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Thanks for letting us know @cjaquino - please let your team know that if they wish to request a new member or merge with another team to make a ticket. 🙏
