### ISSUE TITLE
My team member are not shown in the member list of The Wizard.

### ISSUE THREAD

**Issue by DarisCalinor** [Chingu-cohorts/voyage-wiki#25]
**_Issue Description & Expected Outcome:_** 
My team member Shalini wasn't added our Slack channel in the beginning when the teams are launched. We have found her from team maps, and added to team after, probably manually. Her name is not shown in member list of The Wizard when I typed `/team progress`.

Team Name: geckos-team-20
Member Name: Shalini

Can you please make sure she is added to the team? We start using standups probably in next week.

**_Symptoms:_**
1. Member name is not shown in the member's list of The Wizard as a Team Member.
2. She can create standup, but the standup entry isn't in the Team Standups records.

**Comment by the-vampiire** [comment]
fixed @jdmedlock
