### ISSUE TITLE
Add new member as contributor

### ISSUE THREAD

**Issue by xChristianZx** [Chingu-cohorts/voyage-wiki#250]
**_About You_**
- Voyage number: 6  
- Team Name: Bears - 02
- Slack Name: christianz
- Timezone: UTC -7, PDT

**_Issue Description & Expected Outcome:_** 

Would like to add @adamsackfield as contributor to our repo.  Thanks!

**Comment by tropicalchancer** [comment]
Done! 🎉

**Comment by xChristianZx** [comment]
@tropicalchancer - I meant to follow up on this earlier, but @adamsackfield was never added to our team as a contributor.  Could you please add him.  Thanks!
