### ISSUE TITLE
Only one member is a contributor to the group repo and cannot add other contributors

### ISSUE THREAD

**Issue by jsan4christ** [Chingu-cohorts/voyage-wiki#251]
**_About You_**
- Voyage number ( 6): 
- Team Name: Bears 10
- Slack Name: sanem
- Timezone: GMT +2

**_Issue Description & Expected Outcome:_** 
Only one member has access to the github repo and cannot add contributors. We need to change add all members as contributors.
**_Symptoms:_**
No symptoms
**_Steps to Recreate:_** 
No steps
**_Resolution:_** 
Add members as contributors

**Comment by tropicalchancer** [comment]
Thanks for making a ticket @jsan4christ - I just checked and the invites had been sent before and it says the invites for you and @Tan-Moy are pending. Please check this link to accept invite (or search email history) https://github.com/chingu-voyage6

**Comment by jsan4christ** [comment]
I have accepted the invite. How can I become a contributor to the repo?
