### ISSUE TITLE
Want to leave

### ISSUE THREAD

**Issue by uttamjaiswal86** [Chingu-cohorts/voyage-wiki#256]
**_Uttamjaiswal86 (Team Lead)_**
- Voyage number (6): 
- Team Name: Geckos-Team-23
- Slack Name: Chingu Voyage-6
- Timezone: +530

**_Issue Description & Expected Outcome: I am not getting time to sit and proceed on my project. As My team will have one team partner which need to shift in diff project. I tried for 2-3 week to sit and continue my rest of work but could not able to make to happen. Please sort it out and transfer my mate to diff team_** 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Thanks for making a ticket @uttamjaiswal86 🙏 

Please let let your team-mate know to make a ticket if he'd like a new team to join.
