### ISSUE TITLE
To add a new member to the repo

### ISSUE THREAD

**Issue by jessiepenaloza** [Chingu-cohorts/voyage-wiki#257]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: Toucans-18
- Slack Name: jesica
- Timezone: -3

**_Issue Description & Expected Outcome:_** 
Please add to @anto to our team´s repo. It is toucans-team-18

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
Repo:
https://github.com/chingu-voyage6/toucans-team-18

Thank you.

**Comment by tropicalchancer** [comment]
Added! 🎉

**Comment by jessiepenaloza** [comment]
Thank you very much :)
