### ISSUE TITLE
No response from team

### ISSUE THREAD

**Issue by anujpahade** [Chingu-cohorts/voyage-wiki#259]
**_About You_**
- Voyage number (5 or 6): 6
- Team Name: bears-team-17
- Slack Name: MJarvis
- Timezone: UTC+5:30

**_Issue Description & Expected Outcome:_** 
One of the teammates has hardly participated in the voyage yet.
The other seems to be active only on Mondays for the weekly check-in which has kept me hanging to make this ticket for about 2 weeks.
**_Symptoms:_**
Next to zero activity on the slack group. Email-ids were not shared when asked. Trello ids not shared when asked.
**_Steps to Recreate:_** 
I have messaged them personally multiple times only to get no response or vague responses
**_Resolution:_** 
I know I'm late in making this ticket. But apart from just the new tech, I'm interested in doing well in a team setting. Can I be of some use to other teams or can I get new teammates? I know there are only 5 data scientists in this voyage. Is this even possible?

**Comment by tropicalchancer** [comment]
Message sent in slack
