### ISSUE TITLE
I didn't receive my invite to the github repo of my team

### ISSUE THREAD

**Issue by nirinapf** [Chingu-cohorts/voyage-wiki#26]
**_Issue Description :_** 
I can't find the invite for my team's github repo. I'm in the geckos-team-29. I checked my inboxes and spam folder but I can't find the invite. Also there is no notification in my github account.

**Comment by tropicalchancer** [comment]
Hi @nirinapf! 

Thanks for reaching out. I just checked and it says the invite was sent and is pending? Perhaps check your spam folder in the email associated with your github? 

Let me know if you find it. 👍

**Comment by oschretter** [comment]
Hey, I didn't get my invite for my team's github repo too. I'm in the tucans-team-2. I also checked every inbox.

**Comment by tropicalchancer** [comment]
![image](https://user-images.githubusercontent.com/15321359/36384078-1654bf20-155c-11e8-9d5b-d7c28109da80.png)
🤔 hmmm it says you are already invited as well.

**Comment by nirinapf** [comment]
Hi @tropicalchancer 

Thanks for the taking the time to solve my issue.
I re-checked all the recent mails in my inboxes and spam folder but there is no mail about an invite
.

**Comment by tropicalchancer** [comment]
@nirinapf & @oschretter - can you double check and make sure the email you're checking is connected to your github account? I know  in my case I've got a few emails and have mixed them up before.

**Comment by tropicalchancer** [comment]
@nirinapf & @oschretter - I also just tried cancelling your invite and resending it. Let me know if that works.

**Comment by nirinapf** [comment]
@tropicalchancer  - Thanks, as you said, I mixed my mail, my bad. I thought it was the same adress as the mail adress I use in slack. Really sorry and thanks for taking your time.

**Comment by tropicalchancer** [comment]
No problem at all @nirinapf! I've done it before too...many times 😆
