### ISSUE TITLE
Inactive team member

### ISSUE THREAD

**Issue by BrunoM-Leite** [Chingu-cohorts/voyage-wiki#260]
**_About You_**
- Voyage number (5 or 6):  5
- Team Name: Bruno Leite
- Slack Name: @BrunoLeite
- Timezone: UTC -3

**_Issue Description & Expected Outcome:_** 
@Ishidor been inactive for about 2-3 weekes now. Tried contacting him on discord a few times but not a single answer.
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
I believe is should be just for future reference, because we are already at the end of the trip. No use replacing him and/or merging teams.

**Comment by tropicalchancer** [comment]
Thanks for making a ticket @Yuggin - I'm sorry to hear about @ishidor.

**Comment by brunoleite** [comment]
Why am I being mentioned here?
