### ISSUE TITLE
Inactive Team Members

### ISSUE THREAD

**Issue by hColleen** [Chingu-cohorts/voyage-wiki#261]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Geckos Team 17
- Slack Name: hColleen
- Timezone: MST/AZ Time GMT -7

**_Issue Description & Expected Outcome:_** 
My team member has been inactive for 2 weeks.  I've posted multiple times in slack with no response.
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
I will finish our new tab design as I am almost finished and the deadline is close.

**Comment by tropicalchancer** [comment]
Thanks for making a ticket and letting me know @hColleen. I'm sorry to hear about your team-mate, but happy to see how perseverant you are!
