### ISSUE TITLE
Looking for Team Member 

### ISSUE THREAD

**Issue by JustbeingD** [Chingu-cohorts/voyage-wiki#262]
**_About You_**
- Voyage number (5 or 6):  6
- Team Name:  Gecko-Team 11
- Slack Name: Denis R 
- Timezone: -5 UTC

**_Issue Description & Expected Outcome:_** 
We have lost  a member due to them finding a Job and would no longer be able to participate. An issued was previously created and the new potential member never responded. We have two active members who are committed  to finish our project we are almost finished with our frontend and plan to add backend elements to our project soon. 
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
An additional hand would be a tremendous help.

**Comment by tropicalchancer** [comment]
Message sent in slack
