### ISSUE TITLE
I'd like to add a new team member to our github repo

### ISSUE THREAD

**Issue by ChauTran73** [Chingu-cohorts/voyage-wiki#264]
**_About You_**
- Voyage number (5 or 6): 5
- Team Name: Geckos-7
- Slack Name: ChuChu
- Timezone: New York City

**_Issue Description & Expected Outcome:_** 
I'd luke to add Aruj Joshi with github username as  gtalin to our repo. Thank you.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Done 🎉
