### ISSUE TITLE
Placed in two teams on Voyage 7

### ISSUE THREAD

**Issue by mooneyclan** [Chingu-cohorts/voyage-wiki#274]
**_About You_**
- Voyage number (7): 
- Team Name:  bears-team-10  & geckos-team-12
- Slack Name: ChristCenteredDev
- Timezone: EST

**_Issue Description & Expected Outcome:_** 
I was placed in two teams.  bears-team-10  & geckos-team-12, I would like to know the difference between bears and gecko's then stay in only one team.  I don't think I can keep up with two teams.
**_Symptoms:_**
I was placed in two teams.  
**_Steps to Recreate:_** 
N/A or check Slack
**_Resolution:_**

**Comment by tropicalchancer** [comment]
My mistake - I've removed you from the team that I accidentally added you to.
