### ISSUE TITLE
Not placed in a team

### ISSUE THREAD

**Issue by wiarda** [Chingu-cohorts/voyage-wiki#275]
**_About You_**
- Voyage number 7: 
- Team Name:  ? 
- Slack Name:  Wiarda
- Timezone: GMT+8

**_Issue Description & Expected Outcome:_** 
I haven't been been assigned to a team or received a team channel invite yet

**_Symptoms:_**
-no notification of my team placement received
-no slack channel invitation received
-checked spam folder, but nothing there

Thanks!

**Comment by tropicalchancer** [comment]
My mistake, added the wrong Paul to your team. 

It's fixed now and you've been added 🚀
