### ISSUE TITLE
Not placed in a team

### ISSUE THREAD

**Issue by willybeans** [Chingu-cohorts/voyage-wiki#276]
**_About You_**
- Voyage number (7): 
- Team Name: ?
- Slack Name: Willwedmedyk - display: will
- Timezone: EST

**_Issue Description & Expected Outcome:_** 
I was not assigned to a team
**_Symptoms:_**
There is no team in my slack channels, and no email about being assigned to a team

**Comment by tropicalchancer** [comment]
My mistake, you have been added to your correct team now 🍾
