### ISSUE TITLE
Two members have been transposed

### ISSUE THREAD

**Issue by SalahHamza** [Chingu-cohorts/voyage-wiki#277]
**_About You_**
- Voyage number: 7
- Team Name: geckos-team-23
- Slack Name: Hamza S
- Timezone: UTC+1

**_Issue Description & Expected Outcome:_** 
A member has the same name **Hamza**, which is also the same slack name (I did change mine now to **Hamza S**), which I suppose led to us being mixed up. When I check the Team Map, it is clear that the other member whose git username is @hhamza1 belongs to geckos-team-23, and I belong to geckos-team-19, my git username is @SalahHamza.

I don't have any issue with being in geckos-team-23, it's just the time difference, most people in that team are UTC+5 or UTC+3, while I am UTC+1 (which is not that much I suppose).

Note: I checked team 19, and it seems that the other member already started communicating and brainstorming ideas with his team, if he wishes to stay in that team I don't mind.

**_Symptoms:_**
N/A
**_Steps to Recreate:_** 
N/A
**_Resolution:_** 
N/A

**Comment by tropicalchancer** [comment]
Hey @SalahHamza, 

Thanks for reaching out! 🙏 

I apologize for my mistake. If it's possible to continue as it is (if you are okay with being flexible with the time difference). You mentioned the other Hamza has already started communicating with his team, and it can get difficult to transition when things have already started. 

Let me know what you think.

**Comment by SalahHamza** [comment]
Hey @tropicalchancer 

Yes, of course! I don't mind the time difference, it wouldn't be fair to him, so he can keep on being in team 19.

Thank you so much for the effort!

**Comment by tropicalchancer** [comment]
Thanks for your reply @SalahHamza. Please let me know how it goes and feel free to reach out if you need anything. :)
