### ISSUE TITLE
One member out, another won't be on after Sunday

### ISSUE THREAD

**Issue by jasonmichaels** [Chingu-cohorts/voyage-wiki#279]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: geckos-team-01
- Slack Name: drunkenkismet
- Timezone: EST

**_Issue Description & Expected Outcome:_** 

Lost a teammate on 11/17, and another just informed me they won't be able to be in the cohort after Sunday.

**_Symptoms:_**

Defeat.

**_Steps to Recreate:_** 

Time machine and body-switching.

**_Resolution:_** 

With only me left -- a fourth member has chimed into the team chat one time, indicating they'd be available Monday, but things are looking grim.

**Comment by tropicalchancer** [comment]
Thanks for reaching out @drunkenkismet. Messaged you in slack and added you to a new team. 🍾
