### ISSUE TITLE
Team Slack Channel messages are gone...(nowhere near 10,000 messages)

### ISSUE THREAD

**Issue by kmicks** [Chingu-cohorts/voyage-wiki#28]
**_Issue Description & Expected Outcome:_** 
I checked my slack this morning and the messages we exchanged since Friday were gone.  We had maybe 100 messages, so nowhere near the 10,000 limit where messages start to be cleared.
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by vannya** [comment]
The messages aren't set as a limit of 10,000 messages per channel, but per Slack.  If there is something I need to keep/remember, I throw it in a text document.  I'll post a message in chingu-news that reminds members to save their important information.

**Comment by jdmedlock** [comment]
I keep the important information in the GitHub readme.md or on a Google Drive folder shared with the team, depending on what the information is of course. The choice of where to maintain important team documents is up to each team.
