### ISSUE TITLE
Team Member Left

### ISSUE THREAD

**Issue by evaplaysviolin** [Chingu-cohorts/voyage-wiki#280]
**_About You_**
- Voyage number: 7 
- Team Name: Geckos Team 15
- Slack Name: @eva
- Timezone: UTC-7

**_Issue Description & Expected Outcome:_** 
Member of team left Slack channel.

**Comment by tropicalchancer** [comment]
Thanks for reaching out @evaplaysviolin - I've added a new member to your team. 🍾
