### ISSUE TITLE
Members aren’t very active

### ISSUE THREAD

**Issue by stephen-codes** [Chingu-cohorts/voyage-wiki#282]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: Team Toucans 8
- Slack Name: stephen-codes
- Timezone: GMT -8

**_Issue Description & Expected Outcome:_** 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hello @stephen-codes, thanks for reaching out. 

Can you let us know what you've done to try to make them more active? 

How many messages have you sent? Have you used @username to make sure they are notified? Have you sent each of your team-mates a DM?
