### ISSUE TITLE
Requesting to change tiers

### ISSUE THREAD

**Issue by rrogerthat** [Chingu-cohorts/voyage-wiki#283]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: geckos team 15
- Slack Name: Roger H
- Timezone: UTC-8, PST (California)

**_Issue Description & Expected Outcome:_** I believe a tier-1 team would be a better fit for me at this time. Requesting to be assigned to a tier-1 team. I have informed my current team about my situation and they have acknowledged it.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @rrogerthat - thanks for reaching out. Please reach out to @stephen-codes in Slack to inquire if you can join his team. He made a ticket earlier saying they haven't gotten started yet so that could be a team to join. 

If you do join, please make another ticket so I can add you to the github.

**Comment by rrogerthat** [comment]
Hi Chance,

I reached out to @stephen-codes and will wait for his response. I noticed I
couldn't look up the 2 other members in the group to message. In case this
doesn't fall through, can I possibly start a project of my own for a
landing page?

Thank you,
Roger
