### ISSUE TITLE
Add me to my groups github please.

### ISSUE THREAD

**Issue by ericmillersfbay** [Chingu-cohorts/voyage-wiki#284]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: bears-team-02
- Slack Name: Eric Miller
- Timezone: PST

**_Issue Description & Expected Outcome:_** 
Could you add me to my groups GitHub?

**Comment by tropicalchancer** [comment]
@ericmiller777 you were added and I just checked your invite is still pending. 

Likely your github email is not the you normally check. 

If you go to this URL it should fix it --> https://github.com/orgs/chingu-voyage7/

If it doesn't please let me know.

**Comment by ericmillersfbay** [comment]
Thank you.
