### ISSUE TITLE
Member not Active in GT2

### ISSUE THREAD

**Issue by wiscombetom** [Chingu-cohorts/voyage-wiki#285]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name:  gecko team 02
- Slack Name: wiscombetom
- Timezone: EST

**_Issue Description & Expected Outcome:_** 
Member Kevin S is not active.
We would like to add Hamza S to our team.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
Add Hamza S to gecko team 02 please.

**Comment by tropicalchancer** [comment]
Hey @wiscombetom - that is no problem. He can join your team slack if he hasn't already and I'll send him an invite to the team repo.

**Comment by tropicalchancer** [comment]
He's been added
