### ISSUE TITLE
welcome email

### ISSUE THREAD

**Issue by rpittell** [Chingu-cohorts/voyage-wiki#286]
**_About You_**
- Voyage number (5 or 6): beta hopefully
- Team Name: none yet
- Slack Name: rpittell
- Timezone: EST

**_Issue Description & Expected Outcome:_** 
no welcome email
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hey @rpittell - can you let me know what welcome email you mean? 🙏

**Comment by rpittell** [comment]
The one with the slack details and other info for the start of the new voyage. Unless I just wasn't accepted?

**Comment by tropicalchancer** [comment]
Hi @rpittell - just looked into it further and found the issue. You applied after we did admissions for Voyage-7 and the beta Voyage. You'll be considered for the next beta Voyage in a month or two and we'll reach out then to see if you're still interested. 

Sorry for the confusion 🙏
