### ISSUE TITLE
welcome email not received

### ISSUE THREAD

**Issue by sipofwater** [Chingu-cohorts/voyage-wiki#287]
Hey Chingu's!

I didn't receive my welcome email today for the Winter Beta cohort but I did complete the beta form as was requested from the last email I received after being accepted.

Thanks!
Jake

**Comment by tropicalchancer** [comment]
Hey @sipofwater - were you able to fill out the application on beta? We sent the welcome emails to the emails that submitted that form. 

Let me know and we'll figure it out! :)

**Comment by sipofwater** [comment]
I did and it looked like it submitted successfully.  I don't have a copy of it emailed to me but can't remember if that was an option  or not?

**Comment by tropicalchancer** [comment]
Hey @sipofwater - I've made an issue in the beta feedback repo and tagged the backend team and you in that ticket. Please refer to there for this issue form now on. 🙏
