### ISSUE TITLE
Did not receive receive an invite to the team's repo

### ISSUE THREAD

**Issue by ghost** [Chingu-cohorts/voyage-wiki#288]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: bears-04
- Slack Name: Anass
- Timezone: UTC+1

**_Issue Description & Expected Outcome:_** 
I am the only one in my team to yet receive an invitation to our repo.

**Comment by tropicalchancer** [comment]
Hi @Lunogen - you were added and I just checked your invite is still pending.

Likely your github email is not the you normally check.

If you go to this URL it should fix it --> https://github.com/orgs/chingu-voyage7/

If it doesn't please let me know.
