### ISSUE TITLE
Geckos-team-15 member didn't receive an invite for github

### ISSUE THREAD

**Issue by Sosodope** [Chingu-cohorts/voyage-wiki#29]
**_Issue Description & Expected Outcome:_** 
Geckos-team-15: One member didn't get an invite for github in his inbox.
Team member's slack username is @Jin

**Comment by vannya** [comment]
Invite already resent as noted in Slack.  Please have your member check their email once more.  If they haven't received it, they need to check that their email on Github is correct.

**Comment by vannya** [comment]
Team member confirmed the invite was received.
