### ISSUE TITLE
A teammember dropped out

### ISSUE THREAD

**Issue by anyajunior** [Chingu-cohorts/voyage-wiki#290]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: toucans 17
- Slack Name: Anna B
- Timezone: UTC +3

**_Issue Description & Expected Outcome:_** 
Hey, one of our teammates has just deactivated his account in Slack, having said nothing. Now there are two of us, and I believe we should have one more person! 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hey @anyajunior - thanks for reaching out I will send a message in slack now.
