### ISSUE TITLE
Need waffle integration approved

### ISSUE THREAD

**Issue by jmaldia** [Chingu-cohorts/voyage-wiki#291]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: Bears 11
- Slack Name: jon-maldia
- Timezone: NYC

**_Issue Description & Expected Outcome:_** 
We need the waffle integration approved
![image](https://user-images.githubusercontent.com/1197551/48786336-aa495080-ecb4-11e8-99a2-4baa4eb9ee6b.png)

**_Symptoms:_**
NA 

**_Steps to Recreate:_** 
- Create a new project on Waffle
- Add Voyage 7 as an organization

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hey @jmaldia thanks for reaching out. I approved waffle on this org 🍾
