### ISSUE TITLE
Add member to GT2

### ISSUE THREAD

**Issue by wiscombetom** [Chingu-cohorts/voyage-wiki#292]
**_About You_**
- Voyage number (5 or 6): 
- Team Name: 
- Slack Name: 
- Timezone: 

**_Issue Description & Expected Outcome:_** 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by wiscombetom** [comment]
I don't know why its blank... member is Andres

**Comment by wiscombetom** [comment]
Team is gecko team 2

**Comment by tropicalchancer** [comment]
Thanks for reaching out -

@wiscombetom - just to clarify you want @andres to be added to the Geckos-Team-2 github repo?

**Comment by andres** [comment]
just in case, you got the

wrong @andres

**Comment by wiscombetom** [comment]
Yes please, and added to our chat as well.
Thanks Chance!

**Comment by tropicalchancer** [comment]
Added to the repo - and sent @wiscombetom info on how to add him to your team chat. Cheers! 🍾
