### ISSUE TITLE
Geckos 12: inactive team member

### ISSUE THREAD

**Issue by lgainsbrook** [Chingu-cohorts/voyage-wiki#293]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: Geckos 12
- Slack Name:  lgainsbrook
- Timezone: EST

**_Issue Description & Expected Outcome:_** 
Team member, David -- Slack usename Dline215 -- showed up once to say hi, and hasn't been back for a week. We're happy to have him if someone is able to get in contact with him. Otherwise, we still have 3 team members, but could use a 4th if someone needs a team.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hey @lgainsbrook - thanks for reaching out. When another ticket opens up with someone looking for a team I'll let you know 🙏

**Comment by ReardGjoni** [comment]
Hello @lgainsbrook , Toucans team member with team issues here and looking for another one. I'd love to join and do my best in your team.

Ray

**Comment by abduselamahmed** [comment]
Hey I'm from bears 26 team and if you haven't filled I can join you. Thanks!

**Comment by HixOba** [comment]
@ethioAbduselam , if u need a ideas for a simple project to do, get in touch so i may give u an idea, if u like it and adopt it, it might become easier to find team mates to join you

**Comment by abduselamahmed** [comment]
@HixOba please give me any idea

**Comment by tropicalchancer** [comment]
Member connected to team in slack. :)
