### ISSUE TITLE
GitHub Team access

### ISSUE THREAD

**Issue by chaudhryna** [Chingu-cohorts/voyage-wiki#294]
Hi. This is for or team
- Voyage number 7
- Team Name: Toucan-15
- Slack Name: @SavvasPamboukas
- Timezone: GMT1

**_Issue Description_** 
He can’t access the GitHub Team site.

**Comment by tropicalchancer** [comment]
Hi @chaudhryna - I just checked and you have been added and accepted your invite to the team repo. 

Here is the repo link --> https://github.com/chingu-voyage7/Toucans-Team-15

**Comment by chaudhryna** [comment]
Hi,

It wasn’t for me.  On of the other team members needed access, but I
figured out how to give him access so we’re back on track.

Thank you for following up and thank you so much for creating and working
on Chingu.  It’s a great idea!

Thanks again!

Nancy
