### ISSUE TITLE
Geckos17: Team lost one member, need UI/UX person

### ISSUE THREAD

**Issue by HixOba** [Chingu-cohorts/voyage-wiki#295]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: Geckos 17
- Slack Name: HixOba
- Timezone: UTC+1

**_Issue Description & Expected Outcome:_** 
Team member slack username Giftifytex hasnt turned up since first day hello's. It could be that Giftifytex is having difficulties signing in, dont know/not sure

Rest of team members struggling to cope, perhaps due to busy lives and capability issues

We need an extra hand, good at frontend (React), and comfortable enough to join us while we add a frontend to existing backend.

Flexible about timezone differences, within reason

**_Symptoms:_**
No work done as yet, and i suspect it is probably because levels are misplaced, i might be wrong though but... 
No team meeting involving all members yet, only two members (out of 4) have had a brief conferencing/discussion centred on the chosen project.

**_Steps to Recreate:_** 
Needed: A React/UX/UI person, preferably a capable hand :)
And someone who ia able to give 20+ hours

**_Resolution:_**

**Comment by tropicalchancer** [comment]
To anyone who sees this ticket, please feel to reach out to @HixOba if you think you could fill the role. 🙏

**Comment by HixOba** [comment]
Hi @tropicalchancer  i have @Anshul happy to work with us and be added to the team, but also wants to retain his current team, just in case, is that ok? Meantime we keep it open in case another person is in need.

**Comment by Anshul2166** [comment]
Hi @tropicalchancer  I am in bears-team-6 and am doing my work there, both as developer and as team lead. I saw @HixOba  post for another developer and would be happy to work with them, and my original team in parallel. I can assure you that I would be able to devote sufficient time to both projects.

**Comment by tropicalchancer** [comment]
Hi @Anshul2166 - sounds good you've been added to the geckos-team-17 repo 🍾
