### ISSUE TITLE
Google Feedback Form not functioning as expected

### ISSUE THREAD

**Issue by dirkduplooy** [Chingu-cohorts/voyage-wiki#296]
**_About You_**
- Voyage number (5 or 6):7 
- Team Name: Toucans 2
- Slack Name: dirkduplooy@gmail.com
- Timezone: UTC+2

**_Issue Description & Expected Outcome:_** 
Hallo @Chance it seems the Google Form will not submit and I filled in all the required fields twice and reloaded

@Chance it seems that it is expected that you fill in something in the last 3 response fields after We love to showcase and celebrate our members!
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
hmm @dirkduplooy it might of been because it had a donation link in it. I recall you had issues last time because of this. 

30 people have submitted it so far so it must be working. I removed the donation link so hopefully it will work for you soon.
