### ISSUE TITLE
I need a new team please, if possible

### ISSUE THREAD

**Issue by Danman-01** [Chingu-cohorts/voyage-wiki#297]
**_About You_sss**
- Voyage number (5 or 6): It says Chingu Voyage number 7 on my slack channel.
- Team Name: geckos-team-16
- Slack Name: Dan
- Timezone: GMT+1

**_Issue Description & Expected Outcome:_** My team is inactive and has not replied to anything in our slack channel for several days. Please i would like to join a new team if possible!

**_Symptoms:_** Inactivity of team.

**_Steps to Recreate:_**

**_Resolution:_**

**Comment by ReardGjoni** [comment]
Hello @Danman-01, Toucan member with similar team problems here. Although we are not on the same level I would love to create another team with you and other people who have the same problem and I would give my best to contribute.

Ray

**Comment by tropicalchancer** [comment]
Hey @Danman-01 @ReardGjoni - let me know what you guys decide and I'll make the necessary github changes. 🙏

**Comment by tropicalchancer** [comment]
Added the new member so will close this ticket.
