### ISSUE TITLE
Looking for new teammates

### ISSUE THREAD

**Issue by tiagocorreiaalmeida** [Chingu-cohorts/voyage-wiki#299]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: bears-team-20
- Slack Name: Tiago Correia
- Timezone: WET

**_Issue Description & Expected Outcome:_** 
We lost a team member last week and atm we are looking for 1-2 new team members to join us, those members should be bear level because of the complexity of the project.
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by rachnaban** [comment]
Hi tiagocorreiaalmeida , I am currently a member of Bears-Team-27 but I am the only active member in the team, I work from IST Time Zone.Let me know if you can include me in your team. Currently I am developing some features of google drive using React. 

> **_About You_**
> 
> * Voyage number (5 or 6): 7
> * Team Name: bears-team-20
> * Slack Name: Tiago Correia
> * Timezone: WET
> 
> **_Issue Description & Expected Outcome:_**
> We lost a team member last week and atm we are looking for 1-2 new team members to join us, those members should be bear level because of the complexity of the project.
> **_Symptoms:_**
> 
> **_Steps to Recreate:_**
> 
> **_Resolution:_**
