### ISSUE TITLE
Broken Link In "Section 07. How to Track Issues"

### ISSUE THREAD

**Issue by LuisJaquez** [Chingu-cohorts/voyage-wiki#3]
**_Issue Description & Expected Outcome:_** 
The link "[IdeaNebulae Issue Log](https://github.com/Chingu-cohorts/voyage2-bears-27/issues)" It should lead to a specific repository, but it does not.

**_Symptoms:_**
Shows a 404 error.

**_Steps to Recreate:_** 
N/a

**_Resolution:_** 
N/a

**Comment by Ryan-ED** [comment]
I would have liked to contribute to this but I don't think one can clone and edit a wiki and make a PR to it. So I thought I'd just find the link and send it to you.

Here it is: https://github.com/chingu-voyage3/ideanebulae/issues

**Comment by edward-hong** [comment]
Hi @Ryan-ED, thanks you for the proper link! I've made the change accordingly.
