### ISSUE TITLE
Co-PM addition

### ISSUE THREAD

**Issue by lucygracesmom** [Chingu-cohorts/voyage-wiki#30]
We are Toucans-16 and we have Co-PMs.  @lucygracesmom and @jesica.  Could you make sure @jesica has access to the PM channel? Thank you

**Comment by jdmedlock** [comment]
Assign to Wizard Team

**Comment by tropicalchancer** [comment]
Hi @lucygracesmom, 

I added Jesica to the PM channel.  😄
