### ISSUE TITLE
Zenhub with chingu repo

### ISSUE THREAD

**Issue by willybeans** [Chingu-cohorts/voyage-wiki#300]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: Bears-team-10
- Slack Name: willwedmedyk
- Timezone: est

**_Issue Description & Expected Outcome:_** 
Trying to use zenhub for my chingu teams workflow. It is asking for permission to the repo but i do not have access to the chingu github account.

**_Symptoms:_**
Cannot access the repo when picking from a list of projects in zenhub.

**_Resolution:_** 
Is this as simple as you granting access for my repo, or would it be best if we just chose a different app to organize our workflow?

**Comment by ghost** [comment]
I had this issue too when trying to make gitlab.com a remote. Of course, I can push the files manually, but it would be nice to have automatic sync.

**Comment by tropicalchancer** [comment]
@willybeans your request has been accepted

**Comment by tropicalchancer** [comment]
@barrycarter feel free to send a request

**Comment by ghost** [comment]
@tropicalchancer I think @willybeans' issue is identical to mine, and resolving this issue will resolve mine as well. No need to create a separate issue.

**Comment by willybeans** [comment]
> @tropicalchancer I think @willybeans' issue is identical to mine, and resolving this issue will resolve mine as well. No need to create a separate issue.

Hey barry, my issue has been resolved. if yours hasnt then perhaps you should make a ticket?
