### ISSUE TITLE
Call for more people to join our team

### ISSUE THREAD

**Issue by itaisteinherz** [Chingu-cohorts/voyage-wiki#304]
**_About You_**
- Voyage number: 7
- Team Name: Bears Team 22
- Slack Name: Itai
- Timezone: UTC+2

**_Issue Description & Expected Outcome:_** 

One of the members of my team hasn't been active since the beginning of the cohort, and so we need more people to join our team and help with the development of our project.
If you're interested in making a pretty cool Q&A-style app and know your way around React / MongoDB / Passport.js / Docker / Node.js / Ant Design / other related technologies, please ping me on Slack.

**Comment by tropicalchancer** [comment]
As your request @itaisteinherz - the person you requested has been added. :)
