### ISSUE TITLE
Need to dropout of this cohort to catch up on some work stuff

### ISSUE THREAD

**Issue by kalyantm** [Chingu-cohorts/voyage-wiki#305]
**_About You_**
- Voyage number (5 or 6): 
- Team Name: geckos-20
- Slack Name: kalyantm
- Timezone: GMT + 5:30

**_Issue Description & Expected Outcome:_** 
Need to leave this cohort
**_Symptoms:_**
Things are getting tough at work now and i need to move to another timezone and will be busy for a couple of months. Really sorry, but need to drop out of this one for concentrating at work and hopefully will be able to join a future cohort!
**_Steps to Recreate:_** 
Left the slack group and sent a message to Chance
**_Resolution:_**

**Comment by tropicalchancer** [comment]
@kalyantm did you also let your team know you will be leaving? 🤔
