### ISSUE TITLE
I haven't been invited on my team's github repo

### ISSUE THREAD

**Issue by ChauTran73** [Chingu-cohorts/voyage-wiki#307]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: Gecko-10
- Slack Name: Cmtran7393
- Timezone: ETS

**_Issue Description & Expected Outcome:_** 
I'm not in my team's github repo for Gecko-10

**_Symptoms:_** I can't edit user story and wiki

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @ChauTran73 - I reached out in slack.
