### ISSUE TITLE
I have found a new team member, Please add Ray or ReardGjoni on github to the geckos team 16 repository

### ISSUE THREAD

**Issue by Danman-01** [Chingu-cohorts/voyage-wiki#308]
**_About You_**
- Voyage number (5 or 6): 
- Team Name: geckos-team-16
- Slack Name: Dan
- Timezone: GMT+1

**_Issue Description & Expected Outcome:_** My current team is extremely inactive, but thankfully we found a new member! ReardGjoni, nickname 'Ray' on Slack would like to join Geckos team 16, and gain access to the github repository.

**_Symptoms:_**

**_Steps to Recreate:_** Please add Ray or ReardGjoni on github to the geckos team 16 repository.

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Wonderful @Danman-01 thanks for letting us know! Ray has been added to the Geckos-16 team repo!
