### ISSUE TITLE
Need Organization Invite

### ISSUE THREAD

**Issue by dontehightower** [Chingu-cohorts/voyage-wiki#31]
**_Issue Description & Expected Outcome:_** 
Clicking the link for my organization invite takes me to a page that says:
 "We've looked all over but couldn't find your invitation" 
**_Symptoms:_**
Cannot see Chingu Voyage 4 under my list of Organizations on Github. 
**_Steps to Recreate:_** 

**_Resolution:_** 
Please resend organization invite.

**Comment by tropicalchancer** [comment]
Hi @dontehightower, thanks for reaching out! Looking into it now.

**Comment by tropicalchancer** [comment]
It shows your invite as pending. I cancelled the invite and resent it. 

Can you look now @dontehightower and let me know if it worked?

**Comment by dontehightower** [comment]
Yep! Just accepted it. Thanks for the help & quick response.
