### ISSUE TITLE
Need New Team

### ISSUE THREAD

**Issue by vincentntang** [Chingu-cohorts/voyage-wiki#310]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: Geckos
- Slack Name: Geckos Team 9
- Timezone: EST New York

**_Issue Description & Expected Outcome:_** 
Team disbanded, looking to join another one

**_Resolution:_** 
Looking to do frontend react-development, comfortable with using firebase

**Comment by tropicalchancer** [comment]
Message sent in slack :)
