### ISSUE TITLE
Inactive Team Member 

### ISSUE THREAD

**Issue by ahlvineet** [Chingu-cohorts/voyage-wiki#312]
**_About You_**
- Voyage number (5 or 6):  7
- Team Name: Toucans-05
- Slack Name: vineet
- Timezone: GMT-5

**_Issue Description & Expected Outcome:_** 
One of our team members is missing since last two week. (@varsha)
 & We would like to add @yaronshemesh to our team to get more development bandwidth. 

Please Note:- I was not aware of the ticket system & added @yaronshemesh to our slack group without passing this info to admin.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hey @ahlvineet - thanks for letting me know. @yaronshemesh has been added 🍾
