### ISSUE TITLE
Inactive Team

### ISSUE THREAD

**Issue by kj-gopika** [Chingu-cohorts/voyage-wiki#313]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: Toucans
- Slack Name: KJ
- Timezone: GMT 5.30

**_Issue Description & Expected Outcome:_** Inactive team and members

**_Symptoms:_**No response from team members

**_Steps to Recreate:_** 

**_Resolution:_** 
Trying to learn new things on my own.

**Comment by tropicalchancer** [comment]
Hi @kj-gopika! 

Sent a message in Slack with a possible new team :)

**Comment by tropicalchancer** [comment]
Hey @kj-gopika - you were given a new team but you have not been active 🤔
