### ISSUE TITLE
Need to be added to team to have access to github repo 

### ISSUE THREAD

**Issue by rrogerthat** [Chingu-cohorts/voyage-wiki#314]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: Toucans Team 8
- Slack Name: Roger H
- Timezone: Pacific Time (UTC-7)

**_Issue Description & Expected Outcome:_** Be added to team to be able to push to remote Github repository (https://github.com/chingu-voyage7/Toucans-Team-08)

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hey @rrogerthat -thanks for making a ticket. You've been added :)
