### ISSUE TITLE
Collab access  to Geckos-team-6

### ISSUE THREAD

**Issue by tomasmejia** [Chingu-cohorts/voyage-wiki#316]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: geckos-team-06
- Slack Name:  tomas
- Timezone:  UTC -3

**_Issue Description & Expected Outcome:_** After some tech issues with my laptop, I am finally back to and I can't push to my team's repo since I don't have collab permissions. I need said access to push. 

**_Symptoms:_** N/A

**_Steps to Recreate:_** N/A 

**_Resolution:_**  N/A

**Comment by tropicalchancer** [comment]
Hey @tomasmejia! 

Your invite was sent a few weeks ago and I just checked and it's still pending. You should be able to access by your email or by clicking this link :) --> https://github.com/chingu-voyage7
