### ISSUE TITLE
Need a new team

### ISSUE THREAD

**Issue by RoksySky** [Chingu-cohorts/voyage-wiki#318]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: Geckos-20
- Slack Name: Anastasia
- Timezone: +2.00 (Kyiv timezone)

**_Issue Description & Expected Outcome:_** 
I need a new team.

**_Symptoms:_**
Very low activity of my team. We still can't decide what to code and  I'm not sure we will. They respond for one message during 2 days. They don't respond even when I ask them to.

**_Resolution:_** 
Please find me a new team.

**Comment by tropicalchancer** [comment]
Hey @RoksySky - thanks for making a ticket. Please take a look at some of the open tickets and if a team suits you, feel free to reach out to them. 

If you find a new team let me know and I'll add you to the appropriate github. 🙏

**Comment by tropicalchancer** [comment]
Hey @RoksySky - I found a possible team for you. Please message @Lauren G in slack to let her know you'd like to join their team if they are open to it (she said they are looking for new members to join). 

If you end up joining please make a ticket to let me know so I can add you to the github repo. :)

**Comment by RoksySky** [comment]
Thanks  a lot @tropicalchancer!!! I will surely write to her!
