### ISSUE TITLE
Collaborator Access to Toucans-Team-10

### ISSUE THREAD

**Issue by carolynshin** [Chingu-cohorts/voyage-wiki#32]
**_About You_**
- Team Name: Toucans-10
- Slack Name: carolynshin
- Timezone: Pacific Time

**_Issue Description & Expected Outcome:_** 
Would it be possible for my team and I to have collaborator access to our repository ([toucans-10](https://github.com/chingu-voyage4/Toucans-Team-10))? We may be interested in using GitHub Projects and I noticed I can't do that right now without collaborator access.

**Comment by tropicalchancer** [comment]
Hi @carolynshin! 

Thanks for making a ticket 🙏 Looking into it now!

**Comment by tropicalchancer** [comment]
Hi @carolynshin, it appears this is happening because your invite is pending. Once you accept the invite to the github team, you should have access. 

I resent your invitation so it should be in your inbox (or spam folders). 

Please let me know if this works! 🙏

**Comment by carolynshin** [comment]
This was resolved, thank you @tropicalchancer!
