### ISSUE TITLE
Inactive Team Members 

### ISSUE THREAD

**Issue by Ventrosky** [Chingu-cohorts/voyage-wiki#321]
**_About You_**
- Voyage number 7: 
- Team Name: Bears-Team-21 
- Slack Name: @Ventrosky
- Timezone: UTC+1h

**_Issue Description & Expected Outcome:_** 
One of our team members is absent from the second week (@Yusadolat)
Another team member has been absent for the entire last week (@ALF3run)

**_Symptoms:_**
No commitment to participate and be active

**_Steps to Recreate:_** 

**_Resolution:_** 
Remove inactive members and look for one new member

**Comment by ajaytdev** [comment]
hey is the spot still available ? I would like to work with you guys . two of  my team members are also inactive . I am good with js and bit intermediate in nodejs ecosystem .

**Comment by Ventrosky** [comment]
> hey is the spot still available ? I would like to work with you guys . two of my team members are also inactive . I am good with js and bit intermediate in nodejs ecosystem .

Hi there, the spot is still available, we can chat on slack or meet on discord If you want to know more about the project and see if you are interested 👍

**Comment by ajaytdev** [comment]
Cool , send me the details on slack . username: @dumbwolf  👍

**Comment by tropicalchancer** [comment]
@Ventrosky @ajayt365 please make another ticket if you need me to add anyone to a repo :)
