### ISSUE TITLE
Is it possible to add a non-Chingu member to the team repository please?

### ISSUE THREAD

**Issue by Danman-01** [Chingu-cohorts/voyage-wiki#322]
**_About You_**
- Voyage number (5 or 6): geckos-team-16
- Team Name: geckos-team-16
- Slack Name: Dan - Beingandsoul
- Timezone: 

**_Issue Description & Expected Outcome:_**  Hi Chance, Is it possible to invite a non-Chingu member to the Github repository? I have found a potential new team member to replace some inactive ones. Is it possible to add him to the team repository please?

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by Danman-01** [comment]
My new team members Github is: https://github.com/ABODFTW

**Comment by tropicalchancer** [comment]
Yep, added :)
