### ISSUE TITLE
Need new team

### ISSUE THREAD

**Issue by abby-wankenobi** [Chingu-cohorts/voyage-wiki#323]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: geckos 11
- Slack Name: Abby.wankenobi
- Timezone: NYC (gmt-5)
. 
**_Issue Description & Expected Outcome:_** 

My team is having trouble finding time to talk and plan our project, we all seem to have very different schedules, so I'd like to join another team.

**Comment by tropicalchancer** [comment]
Hey @abby-wankenobi - I recommend looking at this ticket https://github.com/Chingu-cohorts/voyage-wiki/issues/325 and commenting there to see if you can join that team. 

If you end up joining please make another ticket to let me know who to add to what repo :)

**Comment by tropicalchancer** [comment]
No one has reached out on this ticket so will close it 🙏
