### ISSUE TITLE
Toucan Looking for New Team - please comment if you would like a new member :) 

### ISSUE THREAD

**Issue by SoniaTX** [Chingu-cohorts/voyage-wiki#324]
**_About You_**
- Voyage number (7): 
- Team Name: Toucans-7
- Slack Name: 
- Timezone: 

**_Issue Description & Expected Outcome:_** 
My team has one totally inactive member and one member who already has other commitments ( job and school). My team is falling apart like crumbled cookies and not has been communicating for more than two weeks.   

**_Resolution:_** 
Since there was an apparent lack of response from these individuals until this last minute, I feel that this team does not work as a cohesive unit and I request that I be assigned to another team who is more responsive and responsible or the team project be substituted for an individual work project.

**Comment by vwilcox27** [comment]
I'm in the same boat SoniaTX. Want to collaborate?

**Comment by SoniaTX** [comment]
Yes. I was on Toucan Team Number 7. What team were you on?

**Comment by SoniaTX** [comment]
I would like a new member to be joined.

**Comment by tropicalchancer** [comment]
@vwilcox27 @SoniaTX please let me know if you decide to work together and what repo I should add someone to :)

**Comment by SoniaTX** [comment]
Let meet on Slack forum and discuss what to do next. When will you be online on Slack?

**Comment by vwilcox27** [comment]
@SoniaTX Sorry for the late response. It was a long weekend of Christmas parties :) . I was on Toucans 08 team. I'll be on slack all day (I'm on MST time which is GMT -7 I think), so feel free to contact me whenever it's convenient for you. My slack name is Peter Wilcox.

**Comment by SoniaTX** [comment]
Hi Chance,

I would like a new member ( Peter ) to join me.

**Comment by vwilcox27** [comment]
@tropicalchancer SoniaTX and I would like to continue with what Toucans 07 was creating :)

**Comment by tropicalchancer** [comment]
added! 🍾
