### ISSUE TITLE
Toucans-10 - Project manager change

### ISSUE THREAD

**Issue by carolynshin** [Chingu-cohorts/voyage-wiki#33]
**_About You_**
- Team Name: toucans-10
- Slack Name: carolynshin
- Timezone: Pacific

**_Issue Description & Expected Outcome:_** 
- Kevin Micks is our project manager.

**Comment by tropicalchancer** [comment]
@TheSabby - for reference: @kmicks is the slack username

**Comment by tropicalchancer** [comment]
Fixed! 🎉
