### ISSUE TITLE
Please add me to bears-team-21

### ISSUE THREAD

**Issue by nvamsikrishna05** [Chingu-cohorts/voyage-wiki#330]
Hi,

I am joining bears-team-21. So, I would like to get added to their github account.

Thanks,
Vamsi

**Comment by Ventrosky** [comment]
Please add @nvamsikrishna05 to our repo 
https://github.com/chingu-voyage7/Bears-Team-21
:)

**Comment by tropicalchancer** [comment]
@nvamsikrishna05 you've been added 🍾
