### ISSUE TITLE
Add new member to Geckos-Team-23

### ISSUE THREAD

**Issue by sumitjoshi97** [Chingu-cohorts/voyage-wiki#331]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: Geckos-Team-23
- Slack Name: sj
- Timezone: GMT-5:30

**_Issue Description & Expected Outcome:_** 
We are short on members as we are currently only 2 members working on project. But we found a new team member - Alex Nielson, github username - @bushbass to join our team.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
Please add Alex Nielson to our team repository Geckos-Team-23.

**Comment by ajaytdev** [comment]
Do you guys have some backend working with javascript , nodejs ? If you do please give a shout out . I am also looking for a team as my team is completely inactive.
