### ISSUE TITLE
add me to geckos team 12

### ISSUE THREAD

**Issue by vincentntang** [Chingu-cohorts/voyage-wiki#334]
**_About You_**
- Voyage number (5 or 6): 
- Team Name: 
- Slack Name: geckos-team 12
- Timezone: EST

**_Issue Description & Expected Outcome:_** 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
@vincentntang your invite has been pending for a few weeks. 

https://github.com/chingu-voyage7
