### ISSUE TITLE
Remove me from team

### ISSUE THREAD

**Issue by janith-dev** [Chingu-cohorts/voyage-wiki#336]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: Geckos - 22
- Slack Name: JO
- Timezone: UTC +4;

**_Issue Description & Expected Outcome:_** 

- The team is so inactive, No enough contribution commit there time and serious on working a project.
- Progress made so far is negligible when compared to project roadmap and timelines
- Project selected is too simple (From my personal perspective, and does not have enough learning there)

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
- I tried hard to keep things going in this coherent, Respecting the rare chance and opportunity. But is seems i cannot keep thing moving in this project alone.
- I will reapply again for the next coherent.

**Comment by jasonmichaels** [comment]
Hey, @JoleDev -- are you looking to possibly join another cohort? My team is inactive, but I've been pushing ahead anyways. I had no experience with Redux, MongoDB, or Node prior to this, but I've completed a good portion of the front and back ends. Here's my repo: https://github.com/chingu-voyage7/Geckos-Team-18, as well as the deployed Heroku app: https://lit-ridge-25934.herokuapp.com/auth/login. 

Still plenty of work left to do. The design is mostly placeholder stuff, and I'm working on adding the few remaining, huge pieces of the MVP. Do you have strong CSS experience, by chance? Or perhaps knowledge of back-end design?
