### ISSUE TITLE
Please add me as a member to Bears 21 team

### ISSUE THREAD

**Issue by crystalbohacek** [Chingu-cohorts/voyage-wiki#338]
**_About You_**
- Voyage number (5 or 6): 7
- Team Name: Bears-team-01
- Slack Name: 
- Timezone: 

**_Issue Description & Expected Outcome:_** I would like to join Bears team 21 and also remain a member of Bears team 01.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Done!
