### ISSUE TITLE
Unable to pin messages in team's channel

### ISSUE THREAD

**Issue by etorres07** [Chingu-cohorts/voyage-wiki#341]
**_About You_**
- Voyage number (e.g. 8): 8
- Team Name: chimeras-team-02
- Discord Name: Ed
- Timezone: UTC+1

**_Issue Description & Expected Outcome:_** 
I am unable to pin messages to my chimeras-team-02 channel. I would expect to be able to pin others' and my messages for the benefit of the team. 

**_Symptoms:_**
<img width="129" alt="pin" src="https://user-images.githubusercontent.com/38193337/54343316-cd6e8600-463e-11e9-931c-f2f232f98bf6.png">
As you see, I don't have the option.

**_Steps to Recreate:_** 
1. Send the message
2. Click the 3 dots on the upper right corner of the message
3. No 'pin' option is available.

**_Resolution:_** 
I believe this is an admin restriction. I would appreciate any assistance to allow the pinning in my team's chat by me and ideally the other team members. Thanks in advance! 👍 😀

**Comment by jdmedlock** [comment]
Pinning messages requires the "Manage Messages" permission which also allows members of the channel to delete one another's messages. Unfortunately, there is no finer grained permission that only grants the ability to just pin messages. Due to this, we decided not grant this permission.

Will leave ticket open while reviewing this decision.

**Comment by jdmedlock** [comment]
Granted this permission for this team. Closing ticket, but reopen if there are any issues.

**Comment by etorres07** [comment]
No issues here but just wanted to let you know, in case it is relevant, that some of my team members had the ability to pin messages before I opened this issue. Perhaps this information is useful if you are trying to keep these permissions under control. Thanks once again.

**Comment by the-vampiire** [comment]
@eduardoltorres thanks man we sorted that out now
