### ISSUE TITLE
Unable to add myself as a contributor to my team's repo

### ISSUE THREAD

**Issue by hanacaraka** [Chingu-cohorts/voyage-wiki#342]
**_About You_**
- Voyage number: 8
- Team Name: TOUCANS-TEAM-11
- Discord Name: Eri Hariono
- Timezone: GMT +7

**_Issue Description & Expected Outcome:_** 
I'm not sure how to do this (I've already searched in YouTube, but so far nothing explain this thing as a team member for GitHub workflow).

How do we add ourselves as a contributor into my team's repo in Chingu GitHub?
https://github.com/chingu-voyages

Because I have not received the repo invitation email from Chingu GitHub. 

**_Symptoms:_**
I have checked Chingu GitHub and click my team's repo, but to no avail in finding the button or feature to click for adding myself as a contributor.

**_Steps to Recreate:_** 
None

**_Resolution:_** 
<To be completed by Chingu-X team>

**Comment by jdmedlock** [comment]
You should have received an email notification for your GitHub repo that contains a link you'll need to click. If you didn't receive the email check your junk mail folder.

**Comment by the-vampiire** [comment]
![Screen Shot 2019-03-14 at 7 57 50 PM](https://user-images.githubusercontent.com/25523682/54399164-92e30880-4693-11e9-9359-34fb84b266d5.png)

@hanacaraka your invitation is still pending. if you go to [chingu-voyages](https://github.com/chingu-voyages) you will see the invite at the top of the screen.

you should also check which email address you have set as your primary email on github. in the top right go to your profile > settings > emails and see which email is set as [Primary] that is where the invitation was sent.

**Comment by hanacaraka** [comment]
Thanks @jdmedlock & @the-vampiire ! My issue already resolved now.
