### ISSUE TITLE
I didn’t receive Voyage 11  pre-work pack

### ISSUE THREAD

**Issue by ghost** [Chingu-cohorts/voyage-wiki#344]
Email: calogero.napoli92@gmail.com

**Comment by jdmedlock** [comment]
Assigned to Chance. However, the Voyage 11 materials will not go out until August 2nd.

**Comment by ghost** [comment]
Ok, thank you. I’ll wait.

**Comment by tropicalchancer** [comment]
Hi @CalogerN! Your Prep-pack was sent out.:) Please check your spam folders if you haven't seen it yet.
