### ISSUE TITLE
Make a cozier Discord

### ISSUE THREAD

**Issue by etorres07** [Chingu-cohorts/voyage-wiki#345]
**_About You_**
- Discord Name: ed

**_Description & Expectation:_** 
As per my discussion wit @jdmedlock, I humbly bring forward a suggestion to make the Chingu Discord server a tad cozier for the participants.

**_Caveat:_** this suggestion only applies if returning Chingu to Slack is not an option. I elaborate. The supermajority of Chingu participants are looking for a web developer job. Slack is used by companies and their teams to communicate amongst themselves; it is more professional and provides useful functionalities such as message threading. However, I am aware of the free service limitations and this is why I bring the Discord suggestion forward.

# Discord Suggestion

## Roles

At the moment, roles are used for team division and hierarchical identification. I suggest **vanity roles** (I don't suggest that name specifically; I chose it temporarily to refer to them in some way).

Vanity roles are roles participants would be able to assign themselves. The vanity roles I suggest include the following topics: programming skills, personal traits, tiers, and staff.

An example list of roles per topic:
1. Programming skills: React, MongoDB, JavaScript, Python, etc.
2. Personal traits: extrovert, introvert, etc.
3. Tiers: 1-3 for the solo project
4. Staff (_read ahead_)

The way this would work is that participants would be able to self-assign themselves these roles in a specific `#roles` channel (I have seen this in other Discord servers). Each role would have a color and an emoji, if applicable. For example, the MongoDB role would be green with a leaf emoji. The React role would be blue with the atom emoji. And so on.

For the staff roles, I suggest a yellow role called "Minions" for the facilitator minions :)

Besides vanity, roles are also useful for tagging or mentioning specific roles when sharing resources or asking questions.

## Channels with emojis

At the moment, I believe that the channels are named in a fun manner. I think that they could be improved by adding related emojis.

For example:

1. `#chingu-news-prework 📰`
2. `#your-intros-here 🎤`
3. `#ask-questions ❓`
4. Etc.

I also think that the `#not-coding-related` channel from the Central serves the same purpose as the `#community-chat`. Perhaps it could be removed or renamed to something more specific such as SFW (Safe For Work) Memes.

## Custom emojis/Nitro boosters

I believe that creating custom emojis (such as the Chingu logo and The Great Gatsby's) give a more homey vibe to the server. It suggests a Chingu culture. The more emojis, the more homey :) also it might be worth it looking into the Nitro boosters for server perks.

## Voice channels

Create two voice channels, one for general and one for coding. Chingu participants that feel comfortable with this would be able to join these channels and discuss among themselves.

# Steps to Create:
1. **Research:** if conditionally accepted, the first step would be to research how to do this most probably from an admin/mod point of view. Answer question such as: is this free? how to do it? what are the costs of incorporating this or these functionalities? how can these costs be addressed? Is this possible with a Discord bot? Among many other questions
2. **Incorporate:** once the research is done on why and how to do it, do it
3. **Update the Handbook:** for some participants, some of this might be obvious but not for others. Perhaps add a separete "How to Discord" section in the Handbook including and updating the current content
4. **Celebrate:** this is not a _huge_ change but I am confident that participants would have fun setting their roles and looking at each other's roles and colored names

# Resolution
The above is just a general brief for each of the topics therefore I can elaborate where needed. I also volunteer myself for whatever task related to this suggestion you think I could be best suited for. I am happy to contribute in any way you think I can be most useful. I hope that at least some of this could be of use for a better Chingu for tomorrow 🚀

**Comment by jdmedlock** [comment]
Thanks for your suggestions. We'll take a close look at these in the coming days to see which ones we can implement. The only issue I see at this time is using roles to assign personal attributes. Instead, I suggest using the `Note` option in your Discord profile for this. For example, I set mine to:
```
Hard at work on preparations for Voyage 12, which starts on September 12th

Role: Chingu Operations / Admin
TZ: GMT -5
Skills: React, PostgresSQL, JS, HTML, CSS
```
See following comment from Ed. Making profile notes visible to everyone is a feature request made to the Discord team, but they have not committed to implementing it yet.

**Comment by etorres07** [comment]
Thanks for the quick reply. From what I understand, those notes are only visible to the author of the note. I too once thought that it was public.

**Comment by jdmedlock** [comment]
Highlighted Facilitators roles in yellow

**Comment by jdmedlock** [comment]
Status. Added emoticons to Voyage channels. Will followup adding to other channels later. Note that emoticons should *NOT* be added to channels like the team channels which are processed by Chingu-X 'bot until further testing is completed.

**Comment by jdmedlock** [comment]
Question. Since Discord DM's can be used for voice what is the use case for a separate voice channel? Do you mean two channels for each Team or general chat for everyone?

**Comment by etorres07** [comment]
Awesome for the color and emojis!

For the voice channel, this would be the equivalent of the community chat but voice version.

For example, one voice channel called "general-voice" where people just join and leave as they please, there's no need to generate a call. In here, they discuss general topics over voice. Some people might be able to listen but not participate and there can be a corresponding "general-voice-chat", that way these people can also participate in the conversation. They can type in response to the voice conversation. Participants can also share resources (e.g. links) related to their conversation. 

Initially I suggested one voice channel for general topics and another one for code topics, but I think that a general one only would be a good starting point to try out.

Let me know if it's not clear and I'd gladly elaborate or rephrase.

**Comment by jdmedlock** [comment]
Unfortunately, adding animated emoji isn't something we can do at this time since it requires Nitro Boosters which require an additional annual fee. However, we will look at adding additional non-animated emoji.

**Comment by jdmedlock** [comment]
Added the following static (i.e. non-gif) emojis:
:partywizard:
:laptop_parrot:
:confusedparrot:
:githubparrot:
:evilparrot:
:coffeeparrot:
:SkullnCrossbones:

**Comment by jdmedlock** [comment]
Placing this issue in hold status until we can identify funding for Nitro and determine if the cost justifies the benefits.

**Comment by etorres07** [comment]
@jdmedlock sorry for the delay and thank you for the implementations. I've been enjoying them for a while now :)

Regarding Nitro, it is to my understanding that members of the server who are Nitro can contribute "Nitro gems" (or something like that) and it doesn't cost them anything.

Also, if I may ask, why is the personal roles assignation an issue? This is pure curiosity as I have no idea how this works from the admin side

**Comment by jdmedlock** [comment]
I'm glad you asked these questions @eduardoltorres.
1. I haven't see a free option for [Nitro](https://discordapp.com/nitro), even with contribution of functions or features. The base cost of Nitro ranges from USD$4.99-9.99 per month per user. 
2. Using roles as a form of profile is an interesting concept and one that would be applicable in a smaller community. The constraint I'm concerned with is there's a [maximum](https://discordia.me/en/server-limits) of 250 roles per server. Given that we use roles for our automation and that we are growing I don't want to get into a situation where we run out of available roles in a way that impact Voyages. Given the wide variety of profile information to be encoded as roles we could very quickly exhaust our 250 roles. 

We think there is a better solution to sharing profile information across the organization and we'll share it with all Chingu's in the coming months.

**Comment by jdmedlock** [comment]
Closing due to age. Will reopen if needed
