### ISSUE TITLE
Text color difference on Handbook

### ISSUE THREAD

**Issue by RavalVarun** [Chingu-cohorts/voyage-wiki#346]
**_About You_**
- Facilitator
- Discord Name: VarunR
- Timezone: 

**Header Text color on Dark Mode** 
Header text on the handbook isn't readable while reading in dark mode.  

**_Symptoms:_**
The text color in the header makes the header slightly darker and unreadable.
![image](https://user-images.githubusercontent.com/44644972/75072714-0a393300-54c6-11ea-8e5f-21b306117cb4.png)

**_Steps to Recreate:_** 
Happens when dark mode is on.

**_Resolution:_** 
<To be completed by Chingu-X team>

**Comment by jdmedlock** [comment]
Thanks for reporting this! This is acknowledged as a bug and steps are underway to correct it. A staged version with the correction will be made available to you prior to moving the fix into Production.

**Comment by jdmedlock** [comment]
Updates to fix this and broken links in the Pair Programming section have been resolved and promoted to Production.
