### ISSUE TITLE
Departure of a team mate 

### ISSUE THREAD

**Issue by being-shubham19** [Chingu-cohorts/voyage-wiki#36]
**_About You_**
- Team Name: Toucans-team-0
- Slack Name: chingu-voyage-4
- Timezone:  IST

**_Issue Description & Expected Outcome:_** 
One member of the team has left the cohort. So we are expecting a new member to be added so that we can move forward to ACT 2
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @being-shubham19, looking into it now.

**Comment by tropicalchancer** [comment]
Removed the @webcrawler from both the team chat and Voyage due to inactivity.

This is a toucans level project, so two people in a team is perfect. 🚀
