### ISSUE TITLE
Repo invitation 

### ISSUE THREAD

**Issue by cferreirasuazo** [Chingu-cohorts/voyage-wiki#37]
**_About You_**
- Team Name: bears-team-20
- Slack Name: Cristhian Ferreira
- Timezone: utc-4

**_Issue Description & Expected Outcome:_** 
I didnt receive a invitation for my team repo

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @cferreirasuazo! 

Thanks for making a ticket. Looking into it now.

**Comment by tropicalchancer** [comment]
Hi @cferreirasuazo, it says your invite is pending. 

Please look at the email connected to your github account and check spam. I'll cancel and resend the invite to see if that helps. 

Also, let me know if it works and then we'll close this ticket.

Cheers!
