### ISSUE TITLE
I don't have an invite for my team repo

### ISSUE THREAD

**Issue by yordanzhelevdev** [Chingu-cohorts/voyage-wiki#38]
**_About You_**
- Team Name: geckos-team-10
- Slack Name: Misfit
- Timezone: EET

**_Issue Description & Expected Outcome:_** 
I don't have an invite for my team repo. I checked my email but I don't see any invite.
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @yordanzhelevdev! 

Thanks for making a ticket! Looking into it now.

**Comment by tropicalchancer** [comment]
Hi @yordanzhelevdev, it says your invite is pending. I cancelled it and resent it. Please make sure you're checking the email connected to your github account, and check your spam folders as well (it sometimes hides). 

Let me know when you find it and we'll close this ticket. 

Cheers!

**Comment by yordanzhelevdev** [comment]
I already have it. Thank you!

**Comment by tropicalchancer** [comment]
Nice! 🚀
