### ISSUE TITLE
Toucan team 11: Project Manager change.

### ISSUE THREAD

**Issue by AbdulkareemBarghouthi** [Chingu-cohorts/voyage-wiki#39]
Hello, i'm abdulkareem from toucan-team-11.
- Team Name: Toucan-Team-11
- Slack Name: LazyBargh
- Timezone: GMT +2

**_Issue Description & Expected Outcome:_ Our project manager is inactive and not responding to the slack team's channel. The team has decided to make Elle J the project manager (a team member).

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
I've heard whispers that you know this fine gentleman @TheSabby 😀 

Could you remove David and set Elle as the PM? Cheers! 🌮

**Comment by tropicalchancer** [comment]
Ticket has been solved @AbdulkareemBarghouthi! 🎉
