### ISSUE TITLE
Wrong Date in the schedule

### ISSUE THREAD

**Issue by SumanKisku** [Chingu-cohorts/voyage-wiki#4]
Starting date of sprint no. 3 should be 03.01.2018 instead of 02.29.2018.

**Comment by sfiquet** [comment]
Also, assuming all sprints start on a Thursday, all subsequent dates are wrong.

While we're on the subject, would it be possible to change the date format to something like yyyy/mm/dd? I always get confused with the American format, I can't be the only one.

**Comment by jdmedlock** [comment]
Corrected the incorrect date and am reviewing the date ranges with Chance. You are correct that they don't look right. Sprints should begin on Mondays and end on Sundays. I have no issue changing the data formats, but US and Canadian Chingus will have the same issue. Perhaps the best solution is to add a caption defining the date format.

**Comment by sfiquet** [comment]
To be honest I could see the format was mm/dd/yyyy, it's just hard to read correctly when you're used to dd/mm/yyyy even when you know. Maybe instead the dates could follow the American format but with the month in letters (Mmm), that would remove the ambiguity.

**Comment by jdmedlock** [comment]
- Updated dates to ensure that sprints run from Monday to Sunday. 
- Added date format help as a caption to the milestone table. Date format will remain as mm/dd/yyyy. Changing to a different format such as Mmm dd, yyyy alters the flow of the table.
- Lengthened Sprint -1 and shortened Sprint 0
