### ISSUE TITLE
Unresponsive team members - Geckos 9

### ISSUE THREAD

**Issue by zealousAnemone** [Chingu-cohorts/voyage-wiki#40]
**_About You_**
- Team Name: Geckos 9
- Slack Name: Veronica
- Timezone:  EST (NY)

**_Issue Description & Expected Outcome:_** 
Have not yet received responses from 2 of our teammates
**_Symptoms:_**
Unresponsive team mates
**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Thanks for making a ticket @zealousAnemone! 

I will look into this and get back to you by the end of the day! 🏃

**Comment by tropicalchancer** [comment]
@zealousAnemone has been added to Geckos-team-13! 🎉 

Her team-mate may join that team as well or another team.
