### ISSUE TITLE
Repository invititation

### ISSUE THREAD

**Issue by bayramliali** [Chingu-cohorts/voyage-wiki#41]
**_About You_**
- Team Name: toucans-team-1
- Slack Name: Ali Bayramli
- Timezone: CET

**_Issue Description & Expected Outcome:_** 
I already mentioned my issue, but there is no invitation yet.
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by jdmedlock** [comment]
Your invitation was sent and shows as pending. Resending, but please check both your inbox and junk mail. You will have to click on the link in the email to activate.

**Comment by jdmedlock** [comment]
Resolved. User confirms access granted.
