### ISSUE TITLE
Haven't been invited to my Team Repository

### ISSUE THREAD

**Issue by Vukasinn** [Chingu-cohorts/voyage-wiki#44]
- Team Name:  geckos-team-21
- Slack Name:  vasiljevic

I haven't gotten the Email invite to my team repo. *Started writing my github name when I saw I was on github lmao*

**Comment by tropicalchancer** [comment]
Thanks for making a ticket @Vukasinn! 

Looking into it now. 🙏

**Comment by tropicalchancer** [comment]
Ah, I see you've found it 🎉
