### ISSUE TITLE
I haven't been invited to my team repo

### ISSUE THREAD

**Issue by tomektomeknyc** [Chingu-cohorts/voyage-wiki#45]
**_About You_**
- Team Name: gekos-team-29
- Slack Name: tomektomeknyc
- Timezone: GMT+1

**_Issue Description & Expected Outcome:_** 
I haven't received my team repo invitation.
My email: tomektomeknyc@yahoo.com
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @tomektomeknyc! 

Thanks for making a ticket. Looking into it now. 🙏

**Comment by tropicalchancer** [comment]
![image](https://user-images.githubusercontent.com/15321359/36449345-8ed3906e-1658-11e8-8770-09dec2b25edc.png)
Hi @tomektomeknyc your invite had been sent and says pending. I cancelled it and resent it. Please check your email connected to your github account (and check your spam folders as well). 

Cheers! 🎉
