### ISSUE TITLE
Assign PM to team channel Wizard

### ISSUE THREAD

**Issue by valerieseer** [Chingu-cohorts/voyage-wiki#46]
**_About You_**
- Team Name: Bears-Team-13
- Slack Name: @valerie.s
- Timezone: UTC -6

**_Issue Description & Expected Outcome:_** 
That I am assigned as the PM of Bears-Team-13 so I can perform actions on the Wizard.

**_Symptoms:_**
I cannot use the Wizard as the PM. No one can.

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @valerieseer! 

Thanks for making a ticket! 

We're currently working on a way to do this (in a way that won't break things). It may take a few days but in the mean-time, please feel free to use this [text version of the Wizard project roadmap](https://github.com/Chingu-cohorts/pmrok/wiki/Voyage-Roadmap). I apologize for the wait and thanks in advance for your patience 🙏

**Comment by jdmedlock** [comment]
Added to action spreadsheet

**Comment by tropicalchancer** [comment]
Fixed! 🎉
