### ISSUE TITLE
Team member missing on Team Standup

### ISSUE THREAD

**Issue by jmaldia** [Chingu-cohorts/voyage-wiki#47]
**_About You_**
- Team Name: toucans-team-5
- Slack Name: Jon
- Timezone: EST

**_Issue Description & Expected Outcome:_** 
@Sierra (on slack) is missing on our Team Stand up. 

![image](https://user-images.githubusercontent.com/1197551/36454058-6704a2d4-1668-11e8-92d7-22ca601c25d9.png)

**_Symptoms:_**
**_Steps to Recreate:_** 
**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @jmaldia, 

Thanks for making a ticket! 

We're currently working on a way to do this (in a way that won't break things). It may take a few days  and I apologize in advance for the wait 🙏 

We'll reach out as soon as we get it fixed.

**Comment by jdmedlock** [comment]
Added to action spreadsheet

**Comment by tropicalchancer** [comment]
@jmaldia  - Fixed! 🎉
