### ISSUE TITLE
Toucans 16 Team member missing

### ISSUE THREAD

**Issue by lucygracesmom** [Chingu-cohorts/voyage-wiki#48]
**_About You_**
- Team Name: Toucans 16
- Slack Name: lucygracesmom
- Timezone: EST

**_Issue Description & Expected Outcome:_** 
@jesica is on the Toucans 16 team, but is not listed on the team.  She is also supposed to be Co-PM with me. We both have access to PM channel, but she's not listed on our team and neither of us are listed as PM.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by jdmedlock** [comment]
Resolved by #13
