### ISSUE TITLE
Co-PMs needed

### ISSUE THREAD

**Issue by lucygracesmom** [Chingu-cohorts/voyage-wiki#49]
**_About You_**
- Team Name: Toucans 16
- Slack Name: lucygracesmom
- Timezone: EST
**_Issue Description & Expected Outcome:_** 
@jesica and @lucygracesmom are Co-PMs of Toucans-16 and the Wizard is showing Toucans 16 not having a PM.
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @lucygracesmom! 

Thanks for making a ticket!

We're currently working on a way to do this (in a way that won't break things). It may take a few days and I apologize in advance for the wait 🙏

We'll reach out as soon as we get it fixed.

**Comment by jdmedlock** [comment]
Duplicate of #13

**Comment by the-vampiire** [comment]
closes #13  #48
