### ISSUE TITLE
gecko-team-13 - new team members need access to...

### ISSUE THREAD

**Issue by sipofwater** [Chingu-cohorts/voyage-wiki#50]
can we get @Faraz added to our team in Slack?

And our two new team members added to our git repo:
@faraz (username on Slack)
@Veronica (username on Slack)

TIA!

**Comment by tropicalchancer** [comment]
Hi @sipofwater! 

Github invites sent. 

Now, we need to get them showing up on the Wizard, eh?

**Comment by sipofwater** [comment]
Yes, just Faraz is not listed.  I can see Veronica on the repo - I am assuming she can use it now?

Faraz, I don't see listed as a team member - going to assume they have not yet accepted an invite?

Thanks for your help team!

**Comment by fia5000** [comment]
Folks- You have the wrong Faraz. If you find the right Faraz, please ask him to figure out *why* he keeps using my email address to sign up for things

**Comment by sipofwater** [comment]
Wizard needs lyatar removed, and Faraz & Veronica added to the channel (geckos-13):

![selection_999 532](https://user-images.githubusercontent.com/15894446/36514936-f05f27f2-172b-11e8-8e14-143c56f91130.png)

**Comment by sipofwater** [comment]
github user needing adding is mfarazahmad

**Comment by tropicalchancer** [comment]
hey @sipofwater, it appears he is already on it 🎉 cheers!

**Comment by fia5000** [comment]
I'm fucking serious. Whoever _your_ Faraz Ahmad is, its not me. Please take me off this distribution list and off your repository. faraz***@gmail.com belongs to me; I dont know why this other guy is peddling that email address around
