### ISSUE TITLE
gecko5 needs PM assigned

### ISSUE THREAD

**Issue by cewert** [Chingu-cohorts/voyage-wiki#51]
Team Name: **#geckos-team-5**

**_Issue Description & Expected Outcome:_** 
Can you please assign Charlie in slack as the PM for geckos-team-5?

**Comment by tropicalchancer** [comment]
Hi @cewert! 

Thanks for making a ticket!

We're currently working on a way to do this (in a way that won't break things). It may take a few days. Thanks in advance for your patience 🙏

**Comment by cewert** [comment]
Didn't know you guys were having problems thanks for the heads up!

**Comment by cewert** [comment]
Change of plans, can you please make me (Charlie in slack) the PM of geckos5? I'll edit the OP as well so there's no confusion.

**Comment by tropicalchancer** [comment]
@cewert - fixed! 🎉
