### ISSUE TITLE
Toucans-8 needs a PM

### ISSUE THREAD

**Issue by shirlaine** [Chingu-cohorts/voyage-wiki#52]
**_About You_**
- Team Name:  Toucans
- Slack Name: @shirlaine
- Timezone: +8 GMT

**_Issue Description & Expected Outcome_**
-PM/ team member missing in action. Hoping for a new PM to be assigned! Many thanks!

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Reached out to @shirlaine. 

Depending on what they decide, one will likely need to be set as a PM in the wizard.

**Comment by tropicalchancer** [comment]
The team got back to me and will continue as a team of two. We'll make a ticket later for who shall be the PM.
