### ISSUE TITLE
Fou

### ISSUE THREAD

**Issue by fmtabbara** [Chingu-cohorts/voyage-wiki#53]
**_About You_**
- Team Name: geckos 10
- Slack Name: Fou 
- Timezone: GMT + 0

**_Issue Description & Expected Outcome:_** 
I have been added to the team but not to the wizard tools. Also the PM who left the team is still showing under wizard tools as a team member.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
@fmtabbara fixed - cheers! 🎉
