### ISSUE TITLE
Can't install wafflebot on team repo

### ISSUE THREAD

**Issue by sfiquet** [Chingu-cohorts/voyage-wiki#54]
**_About You_**
- Team Name: Bear-19
- Slack Name: @Sylvie
- Timezone: UTC +0

**_Issue Description & Expected Outcome:_** 
I can't install the Wafflebot. 

According to https://help.waffle.io/wafflebot-basics/wafflebot-faqs/can-i-install-wafflebot-in-my-organization only an owner is allowed to install Wafflebot, which would explain it.

**_Symptoms:_**
Only my own repos are available to select in the install screen.

**_Steps to Recreate:_** 
- I have added my team's repo in Waffle.
- From the team repo's board, when I click on the wafflebot option either in the main menu or the project settings, I can see the 'Configure Wafflebot' button.
- When I click on it, it opens the GitHub Apps page for Wafflebot in a new tab.
- When I click the install button, I can only install to one of my repos:

![screen shot 2018-02-21 at 09 29 50](https://user-images.githubusercontent.com/4646869/36472500-f000f03e-16e9-11e8-842b-970f0962f8d3.png)

**_Resolution:_**

**Comment by jdmedlock** [comment]
I think I know what the issue is. In waffle.io click on the `Create Project` button next to ‘Your Projects’. On the Create a Project page click on your name and you should see a drop down menu listing yourself and all the organizations you are authorized for. Next click ’chingu-voyage4, then your project from the list of repos, and finally the ‘continue’ button’

**Comment by sfiquet** [comment]
I just followed your instructions but the result is the same (I'm pretty sure I also did that initially).

**Comment by jdmedlock** [comment]
Wafflebot installation now requires an organization owner perform the installation. This appears to be a change from Voyage3 where we didn't do this for teams who choose to use it. Verified that assigning Collaborator access has no effect. 

Added this to Voyage4 Retrospective Items for further research.
