### ISSUE TITLE
Team members missing

### ISSUE THREAD

**Issue by Smithmayowa20** [Chingu-cohorts/voyage-wiki#55]
**_About You_**
- Team Name: Bears Team 29
- Slack Name: @smithmayowa
- Timezone: GMT + 1 

**_Issue Description & Expected Outcome:_** One of my team member has not been available at all since joining our team channel and the other is not always around. We really have not even had a meeting to determine what project we should execute on.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @Smithmayowa20, I reached out to you and @Nedu in Slack. Once I get a response we can move forward. 🙏

**Comment by Smithmayowa20** [comment]
@chance I feel redistribution will be best

**Comment by SmithMayowa** [comment]
@chance I think redistribution will be the best way forward.
