### ISSUE TITLE
toucans-team-1 team wizard workflow and restructure

### ISSUE THREAD

**Issue by dirkduplooy** [Chingu-cohorts/voyage-wiki#56]
**_About You_**
- Team Name: toucans-team-1
- Slack Name: dirkduplooy
- Timezone: UCT +2

**_Issue Description & Expected Outcome:_** 
dirkduplooy to be set as PM and alibayramli to be removed from team and possible new member to be assigned from disbanded teams
**_Symptoms:_**
dirkduplooy have a headache
**_Steps to Recreate:_** 
Get knot in stomach
**_Resolution:_** 
dirkduplooy was made PM

**Comment by jdmedlock** [comment]
Change of role to PM for dirkduploy added to action spreadsheet. 
Removal of alibayramli not added to action spreadsheet pending review with Chance
