### ISSUE TITLE
Bears-team-20 team member left

### ISSUE THREAD

**Issue by marianoheller** [Chingu-cohorts/voyage-wiki#57]
**_About You_**
- Team Name: Bears-team-20
- Slack Name: marianoheller
- Timezone: UTC-3

**_Issue Description & Expected Outcome:_** Team member @cjlynch12 left the cohort due to family/personal reasons. (and wants to be able to join another cohort in the future)

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Noted, and thanks for letting us know @marianoheller! 🙏
