### ISSUE TITLE
Request for distribution of Bear Team 29 members

### ISSUE THREAD

**Issue by Smithmayowa20** [Chingu-cohorts/voyage-wiki#58]
**_About You_**
- Team Name: Bears Team 29
- Slack Name: @smithmayowa
- Timezone: GMT + 1

**_Issue Description & Expected Outcome:_** Due to the sad state and slow progress experienced by Bear team 29 due to the perpetual absence of some of its team members, and after careful consideration of the options laid down before us by chingu administrators, I hereby humbly request for the distribution of the active members of bear team 29 to other teams.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @Smithmayowa20! 

Thanks for getting back to me 🙏 I've got a potential new home for you just need to confirm with the team and then I'll let you know.

**Comment by Nedu** [comment]
Hi @tropicalchancer do I need to open a separate issue or will this issue be enough?

**Comment by tropicalchancer** [comment]
@Smithmayowa20  - fixed! 🎉

**Comment by tropicalchancer** [comment]
@Nedu - I've sent you a DM in slack and we'll go from there. I'll close this ticket but add you to the free-agents list (and we'll discuss team transition options in slack)
