### ISSUE TITLE
The Wizard is not recognizing me as the Project Manager

### ISSUE THREAD

**Issue by Briahna** [Chingu-cohorts/voyage-wiki#59]
**_About` You_**
- Team Name: geckos-team-2
- Slack Name: Briahna
- Timezone: CST

**_Issue Description & Expected Outcome:_** 
When I try to check team progress or set a milestone, I am told that I am not the Project Manager

I expect to be able to set milestones and I expect to be listed as a project manager when checking team progress.

**_Symptoms:_**

The Project Manager row says "PM not set" when checking team progress.
No one can set milestones.

**_Steps to Recreate:_** 
Checking team progress.
Attempting to set milestone.
Attempting to ask team members to submit stand-ups.

**_Resolution:_**

**Comment by jdmedlock** [comment]
Added to action spreadsheet

**Comment by tropicalchancer** [comment]
Fixed 🎉
