### ISSUE TITLE
Trello, Waffle.io and ZenHub links not working

### ISSUE THREAD

**Issue by 8thDay** [Chingu-cohorts/voyage-wiki#6]
The last 3 links on the `Section 03. Establishing the Team` page of the wiki, which should lead to Trello, Waffle.io and ZenHub, are not working.

The links currently point to:

- https://github.com/Chingu-cohorts/voyage-wiki/wiki/www.trello.com
- https://github.com/Chingu-cohorts/voyage-wiki/wiki/www.waffle.io
- https://github.com/Chingu-cohorts/voyage-wiki/wiki/www.zenhub.com

and are redirecting to the wiki home page when clicked.

**Comment by jdmedlock** [comment]
Thanks again for reporting this error. The issue was a missing `https://` prefix on the URL's. Resolved
