### ISSUE TITLE
Toucans-team-0 good to go with 2 members 

### ISSUE THREAD

**Issue by being-shubham19** [Chingu-cohorts/voyage-wiki#60]
**_About You_**
- Team Name: Toucans-team-0
- Slack Name: chingu-voyage-4
- Timezone: IST

**_Issue Description & Expected Outcome:_** 
We are good to go with only 2 team members
**_Symptoms:_**
Already decided the project and work distributed as well
**_Steps to Recreate:_** 

**_Resolution:_** 
Wish us luck 😉

**Comment by tropicalchancer** [comment]
🎉 🙏  🎉
