### ISSUE TITLE
PM is missing

### ISSUE THREAD

**Issue by cadmoral** [Chingu-cohorts/voyage-wiki#61]
**_About You_**
- Team Name: Geckos team 18
- Slack Name: carla / cams_00
- Timezone: 

**_Issue Description & Expected Outcome:_** 
Our PM has been absent since the beginning of the voyage.
Assign another PM and/or include someone that would like to be PM.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Thanks for making a ticket @cadmoral! 

Sent DM in slack, removed lech from the team/ voyage.

Once I get a response, we'll give the decided Wizard wielder access tot he wizard 🚀

**Comment by tropicalchancer** [comment]
Fixed 🎉
