### ISSUE TITLE
I don't have a team

### ISSUE THREAD

**Issue by RA9** [Chingu-cohorts/voyage-wiki#62]
**_About You_**
- Team Name: NO Team yet
- Slack Name: Carlos Nah
- Timezone: 

**_Issue Description & Expected Outcome:_** 
Hi , I was invited sometime two weeks ago I introduced myself and signup the form on https://chingu.io/signup and after that I was very active for almost a week before I left to run after my process and after  completing my  college entrance I decided  to come and apologize for my disappearance and out of a sudden I  can't  see my slack chingu-voyage4 so I decided to  check my mail and it says I was invited by Van Tabbert but when I click the link it says error also looking through my mail it say a message from github your invitation has been canceled And I don't know why ? 
so my question is am I or am I not taking part in the chingu-voyage4?
**_Symptoms:_** 

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @RA9, thanks for reaching out with a ticket. I just sent you an email. 🙏
