### ISSUE TITLE
Incorrect project manager assigned and access to PM slack channel.

### ISSUE THREAD

**Issue by kmicks** [Chingu-cohorts/voyage-wiki#63]
**_About You_**
- Team Name: Toucans-team-10
- Slack Name: kmicks
- Timezone: CST (-6GMT)

**_Issue Description & Expected Outcome:_** 
I am the team project manager.  The individual listed as PM is not correct for my group.  Also, I do not have access to the #project-manager channel.  Thanks!

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Thanks @kmicks! 

Invite to PM channel sent. 🎉 

Wizard access should be available by tomorrow. 😄

**Comment by tropicalchancer** [comment]
@kmicks fixed!
