### ISSUE TITLE
Inactive member

### ISSUE THREAD

**Issue by CatVeiga** [Chingu-cohorts/voyage-wiki#64]
**_About You_**
- Team Name: Toucans - Team - 9 
- Slack Name: Ana Veiga
- Timezone: WET

**_Issue Description & Expected Outcome:_** 
A member of our team (Hussein on Slack) is still not active, and it is with great regret, that I have to open this ticket. I've talked to him, we tag him several times, and he does not show up. When he is online he never comes to us, not even to say hello, he is not giving his contribution, he only agrees with everything. 
We all understand that he has to work and study and he applied only part-time here, but even that he does not do it ... his only "contribution" was on Monday. : / Yesterday appeared in Slack, saying that he wants to help us, but does not know how to use things, we try to talk with him, to ask ... we do not get anything from him. At this moment, when we are deciding important things to start sprint 1, It seems to me unfair to keep him on the team...he was the only one not to do a Standup, I do not know what else to do, because another member came to me, say that she was frustrated that he did not help or contribute. 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
@cveiga819 thanks for making a ticket! 🙏 

Fixed! 🎉
