### ISSUE TITLE
slack

### ISSUE THREAD

**Issue by Anja** [Chingu-cohorts/voyage-wiki#65]
**_About You_**
- Team Name: toucans 7
- Slack Name: anna
- Timezone: +1 utc

**_Issue Description & Expected Outcome:_**  why did you remove me from Slack channel?

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @Anja, sent email. 🙏
