### ISSUE TITLE
Change of Project Manager

### ISSUE THREAD

**Issue by blesschews** [Chingu-cohorts/voyage-wiki#66]
Hello, i'm blessing from gecko-team-36.

Team Name: gecko-Team-36
Slack Name: LazyBargh
Timezone: GMT +2
**Issue Description & Expected Outcome: The project manager is currently overwhelmed. As a team we have agreed to swap roles angd give the Project manager role to MartLepanen
Symptoms:

**Comment by jdmedlock** [comment]
| Current Role | New Role |Slack Name | GitHub Name | email |
|:-------------|:----------|:------------|:--------------|:------|
| PM | Team Member | LazyBargh | AbdulkareemBarghouthi | k.bar123@hotmail.com |
| Team Member | PM | MartLepanen | Martialis39 | mart_lepanen@hotmail.com |

**Comment by tropicalchancer** [comment]
Thanks for making a ticket @blesschews! 

Fixed! 🎉
