### ISSUE TITLE
Join in future voyage - psongpin

### ISSUE THREAD

**Issue by jdmedlock** [Chingu-cohorts/voyage-wiki#68]
**_About You_**
- Team Name: N/a
- Slack Name: psongpin
- Timezone: Unknown

**_Issue Description & Expected Outcome:_** 
In #chingu-central Paul has expressed his desire to join in a Voyage:
- "Hey guys I have been long lurking here. Im just wondering were can I find those groups here in chingu that are building projects?"
- "hi @pai I want to join those build-to-learn teams and build something useful opensource projects"

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Moving this into FREE-AGENTS ticket 🌮
