### ISSUE TITLE
Need Github Project Access

### ISSUE THREAD

**Issue by dontehightower** [Chingu-cohorts/voyage-wiki#69]
**_About You_**
- Team Name: Geckos-Team-18
- Slack Name: @Donte
- Timezone: UTC -6

**_Issue Description & Expected Outcome:_** 
I was recently re-assigned to Geckos-18, but haven't been added to the project on GitHub yet

**_Resolution:_** 
Please add me to the Geckos-Team-18 project

**Comment by jdmedlock** [comment]
Added to Geckos-Team-18. DM'ed on Slack to verify access, but no reply. Closing, but feel free to reopen this issue if the problem persists.
