### ISSUE TITLE
Possible typo in Section 04. Setting Up Your Git Workflow

### ISSUE THREAD

**Issue by 8thDay** [Chingu-cohorts/voyage-wiki#7]
>**Git Branches**
...
 development: Reflects the candidate code for the next release. Developers work in developer branches, which are then pulled into this branch.

Should this read:
_development: Reflects the candidate code for the next release. Developers work in `working` branches, which are then pulled into this branch._

**Comment by jdmedlock** [comment]
Thank you for reporting this. Resolved following your recommendation.
