### ISSUE TITLE
Project Manager Change Request

### ISSUE THREAD

**Issue by fancyaction** [Chingu-cohorts/voyage-wiki#70]
**_About You_**
- Team Name: Toucans-Team-3
- Slack Name: FancyAction
- Timezone: UTC-6

**_Issue Description & Expected Outcome:_** Our PM left Chingu due to work. 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** I'd like to be assigned the role so I can make some progress setting things up. Our other remaining member, who is away traveling until Tuesday, agreed with this. If we get a new member this week, way may open discussion again on who should be PM.

In addition, a new toucans-team-17 was opened for us but it should be closed since our initial channel already has progress we'd like to keep (Waffle, Apps, chat history, etc.). Thanks!

**Comment by jdmedlock** [comment]
Let's wait until the there's a permanent choice for PM so this only has to be done once. Placing this ticket on Hold

**Comment by fancyaction** [comment]
Yes, my teammate is okay with this. In their words (earlier today): "I am cool if you want to be the pm"

I spoke to Chance and he said I should take PM role and stick with it. I didn't realize it's time-consuming task for you to change on the back-end. Since that's the case, I'll stick with it and try my best. 

It's important that I get access and start setting things up, so we can hit the ground running when Karthik returns Wednesday. Right now, we have nothing done or setup.

**Comment by tropicalchancer** [comment]
Request sent! 😄 Will close when confirmation comes in
