### ISSUE TITLE
geckos-team-23 member has not participated in any team communications/meetings

### ISSUE THREAD

**Issue by EmmieO** [Chingu-cohorts/voyage-wiki#71]
**_About You_**
- Team Name: geckos-team-23
- Slack Name: @Emmie
- Timezone: CST

**_Issue Description & Expected Outcome:_** 
One of my team members, @Methodbox is not participating with the team.  I have attempted to communicate with him via DM, but there's been no response.

**_Symptoms:_**
@Methodbox has not checked in or communicated with the team.  The only  "communication" I've had was when he declined the meekan invitation for our first team meeting.

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @EmmieO! 

Thanks for making at ticket. Looking into this today and will reach out in a DM soon 🙏

**Comment by tropicalchancer** [comment]
@methodbox has been removed from the team and voyage for not participating in his/her team.
