### ISSUE TITLE
I'm not in the organisation.

### ISSUE THREAD

**Issue by raizen62** [Chingu-cohorts/voyage-wiki#72]
**_About You_**
- Team Name: Bears-21
- Slack Name: raizen62
- Timezone: +2

**_Issue Description & Expected Outcome:_** 
I'm not in the chingu-voyage4 organization and I can't contribute to the repo.

**Comment by tropicalchancer** [comment]
Hi @raizen62, I checked your team and it said invite was pending for you. Please check the email connected to your github account. I cancelled and resent the invite so it should show up again (might be in a spam folder). Cheers! 🎉
