### ISSUE TITLE
Can't wafflebot

### ISSUE THREAD

**Issue by sipofwater** [Chingu-cohorts/voyage-wiki#73]
**_About You_**
- Team Name: Geckos-Team-13
- Slack Name: sipofwater (jake)
- Timezone: PST

**_Issue Description & Expected Outcome:_** 
When creating a branch with waffle issue # in branch name, for waffle to move from Inbox to In Progress
Cannot view our repo with wafflebot integration on github

**_Symptoms:_**
Cannot bring up "Chingu..." or "Geckos..." when trying to setup wafflebot in github
I am assuming this is a permissions problem?

**_Steps to Recreate:_** 
Create Issue on Waffle.io  
Create local branch (have tried several naming conventions, none seem to work, both locally and on github)
Does not move from Inbox to In Progress on waffle.io
The repo is listed under Project Settings -> Repositories  
Cannot connect repo under Project Settings -> Wafflebot

**_Resolution:_** 

![selection_999 620](https://user-images.githubusercontent.com/15894446/36701972-1b7b542e-1b0a-11e8-808d-e21b5e6155bb.png)
![selection_999 621](https://user-images.githubusercontent.com/15894446/36701971-1b5d6e8c-1b0a-11e8-8930-5d27cf9faa7e.png)

**Comment by jdmedlock** [comment]
Created new issue in waffle.io for the Geckos 13 team and changed it's label to 'In Progress'. Refreshed browser page and noted that the task was moved to 'In Progress' as expected. 

However, I've noticed that when a test issue's label is changed to 'in progress' within GitHub the task is correctly moved to the 'In progress' silo when viewing the repo from within [waffle.io](https://waffle.io/chingu-voyage4/Geckos-Team-13). However, when viewing the repo from within GitHub using the 'Board' option all tasks are residing under 'New Issues'.

This indicates that Wafflebot is active and working. However, I would have expected the GitHub view to match the Waffle.io view.

I did notice that there were two failed payloads today. 

![image](https://user-images.githubusercontent.com/1287072/36704384-be322416-1b25-11e8-9d85-3fc330b5f801.png)

I have verified that the members of Geckos-Team-13 all have admin privileges against this repo. 
![image](https://user-images.githubusercontent.com/1287072/36704502-3f4170a2-1b26-11e8-9adc-d54f5149087a.png)

If this list includes everyone on your team I suggest that you open an issue with Waffle Support regarding this problem.

**Comment by jdmedlock** [comment]
Leave this ticket open pending further investigation and potentially ticket with Waffle.io

**Comment by jdmedlock** [comment]
Posted in Slack - ChinguVoyage-4/#code-help:
```
Jdmedlock Today at 7:07 AM 
See the comments in the ticket below. I suggest opening an issue with Waffle.io Support. 
I can make issues move by changing their labels in Waffle.io, but not from the Board view 
within GH. https://github.com/Chingu-cohorts/voyage-wiki/issues/73.

However, I did just find this in the Waffle.io FAQ. https://help.waffle.io/faq/waffle-workflow/why-are-my-issues-in-backlog-being-automatically-moved-to-in-progress
```

**Comment by the-vampiire** [comment]
@jdmedlock can close this one and other related. awww yeee

**Comment by jdmedlock** [comment]
Resolved by granting Wafflebot access to all `Chingu Voyage-4` repos.
