### ISSUE TITLE
Can not take team standups

### ISSUE THREAD

**Issue by Smithmayowa20** [Chingu-cohorts/voyage-wiki#75]
**_About You_**
- Team Name: Bears-Team-21
- Slack Name: smithmayowa
- Timezone: GMT + 1

**_Issue Description & Expected Outcome:_** I changed my teams and from bears-team-29 to bears-team-21 and I sadly cannot take standups in my new teams slack as I am not included in the wizards app members list for my new team.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Looking into now @Smithmayowa20 🙏

**Comment by tropicalchancer** [comment]
Done @Smithmayowa20 🎉
