### ISSUE TITLE
Adjustments requested to Toucans-Team-3

### ISSUE THREAD

**Issue by jdmedlock** [Chingu-cohorts/voyage-wiki#76]
**_About You_**
- Team Name: Toucans-Team-3
- Slack Name: sparta
- Timezone: 

**_Issue Description & Expected Outcome:_** 
Via Slack:
```
Another guy and I decided to join another group to help out with their pairings.
Their teams pretty much fell apart with no communication/members leaving, etc.
I'd still be in my original group and would be helping out this second group part
time. All parties involved are aware and are OK with the time commitment.

Would you be able to invite the new members into the group repo?

The group repo is Toucans-Team-3. Members that need to be invited are :

- `mrbrackins`
- `Bigghead` (edited)

Any help is super appreciated, Jim
```
**_Symptoms:_**
N/a

**_Steps to Recreate:_** 
N/a

**_Resolution:_**

**Comment by jdmedlock** [comment]
Related to issue #70

**Comment by jdmedlock** [comment]
| Current Role | New Role |Slack Name | GitHub Name | email |
|:-------------|:----------|:------------|:--------------|:------|
| N/a | Team Member | Tony | mrbrackins | tony@mrbrackins.com  |
| N/a | Team Member | sparta | Bigghead | shavenchew@yahoo.com |

**Comment by tropicalchancer** [comment]
Thanks for making a ticket monsieur @Bigghead! 

Github team invites have been sent and will put a request in with the :party-wizards: (it may take a few days for your usernames to showup in the wizard)

**Comment by tropicalchancer** [comment]
Done 🎉
