### ISSUE TITLE
Remove abandoned member from Toucans-Team-3

### ISSUE THREAD

**Issue by fancyaction** [Chingu-cohorts/voyage-wiki#77]
**_About You_**
- Team Name: Toucans-Team-3
- Slack Name: fancyaction
- Timezone: UTC-6

**_Issue Description & Expected Outcome:_** Aparna left Chingu and our group last week. Their departure was amicable and understood -- hopefully they return on a future voyage! However, their name still shows in standups and is a member of our repo. Not a big deal but would be nice if we could get that cleaned up, when the Chingu gods have some free time. Thanks!

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** Remove Aparna from Slack wizard and Toucans-team-3 repo.

**Comment by jdmedlock** [comment]
| Current Role | New Role |Slack Name | GitHub Name | email |
|:-------------|:----------|:------------|:--------------|:------|
| PM | N/a | Aparna | apnair15  | apnair15@gmail.com  |

**Comment by jdmedlock** [comment]
Completed removal of `apnair15` from the GitHub Toucans-Team-3. Note that wizard adjustments still need to be made to remove this user.

**Comment by the-vampiire** [comment]
Aparna has been removed
