### ISSUE TITLE
I want to quit the project, talked with my PM, wanted to give you info also.

### ISSUE THREAD

**Issue by ucanfil** [Chingu-cohorts/voyage-wiki#79]
**_About You_**
- Team Name: bears-team-19
- Slack Name: Burak T.
- Timezone: UTC+3

**_Issue Description & Expected Outcome:_** 
I dont know if you can recall but im the one who has basic front end skills and yet assigned to bears-team-19. 
Since i'm not experienced at back-end even at the setup stage this chingu took more time than i can give weekly basis, i want to apply a bootcamp in London and its application deadline ends at the end of april, they require to reach 5kyu at codewars. I thought i can share some of my time here but within this Tier i am not able. 
Talked with my PM and i want give info to you guys also. Thank you for having me, hopefully this doesnt brake our relationship.
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
Remove Burak T. from Slack wizard and bears-team-19 repo.

**Comment by jdmedlock** [comment]
| Current Role | New Role |Slack Name | GitHub Name | email |
|:-------------|:----------|:------------|:--------------|:------|
| Team Member | N/a | Burak T. | ucanfil  | buraktilek@hotmail.com  |

Removed user from GitHub repo. Wizard updates must still be performed

**Comment by tropicalchancer** [comment]
Burak has been removed. Replacement has been found. 🎉
