### ISSUE TITLE
Link to Carnegie wisdom article missing from FAQ

### ISSUE THREAD

**Issue by 8thDay** [Chingu-cohorts/voyage-wiki#8]
In `Section 99. Frequently Asked Questions`, in the section titled "[Are Soft Skills Important?](https://github.com/Chingu-cohorts/voyage-wiki/wiki/Section-99.-Frequently-Asked-Questions#are-soft-skills-important)" 

The last line, which reads `Here are 30 soft skill principles that can level-up your skills `, should (presumably) have a link to the following article:
https://medium.com/chingu/30-ways-to-level-up-your-skills-stack-carnegies-wisdom-remix-4c532aabd0c0
(As per the "Chingu Voyage-4 Prep Pack" email)

**Comment by jdmedlock** [comment]
Resolved issue as described above. 

Another good catch on your part. Thanks for reporting this issue.
