### ISSUE TITLE
Toucans-Team-11 may need another Team Member

### ISSUE THREAD

**Issue by atarsa** [Chingu-cohorts/voyage-wiki#80]
**_About You_**
- Team Name:  Toucans-Team-11
- Slack Name:  @Agnieszka
- Timezone: UTC +0

**_Issue Description & Expected Outcome:_** 
Due to personal reason, I can't participate in Chingu anymore. Toucans 11 will be down to two members and may be in need of another Team Member. 
Really sorry about this! 
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** 
Remove Agnieszka from Slack wizard and toucan-team-11 repo.

**Comment by jdmedlock** [comment]
| Current Role | New Role |Slack Name | GitHub Name | email |
|:-------------|:----------|:------------|:--------------|:------|
| Team Member | N/a | Agnieszka | elPetit69  | smb909@gmail.com  |

Removed user from GitHub repo. Wizard changes must still be performed.

**Comment by tropicalchancer** [comment]
Ticket closed. There are no free-agent toucans to add so the team will have to remain as is. If someone emerges I'll reach out.
