### ISSUE TITLE
Team member missing from Github team member list

### ISSUE THREAD

**Issue by dontehightower** [Chingu-cohorts/voyage-wiki#81]
**_About You_**
- Team Name: Gekcos-Team-18
- Slack Name: @Donte
- Timezone: UTC -6 

**_Issue Description & Expected Outcome:_** 
Please add @Marcus, to Geckos-Team-18 project on Github

 Github: https://github.com/mjd123 to 
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Hi @dontehightower, I checked and his invite was pending already. I cancelled it and resent it. 🎉
