### ISSUE TITLE
Enable Chingu members on 2 teams to access two different standups

### ISSUE THREAD

**Issue by fancyaction** [Chingu-cohorts/voyage-wiki#82]
**_About You_**
- Team Name: Toucan-team-3
- Slack Name: fancyaction
- Timezone: utc-6

**_Issue Description & Expected Outcome:_** Sparta joined our team (toucans-team-3) as his 2nd current team but found his standup gets overwritten when writing them in our Slack channel. Is there a way to give him two separate standups in the wizard (one for each team channel -- sorry, I'm not sure what his original team is)?

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** If this is too big of an issue to solve -- perhaps it's tied to Slack username -- I advised him to use the Notes field for our team. If this can be solved within the wizard though, that would be sweet!

**Comment by jdmedlock** [comment]
Routing to Wizard team.

**Comment by the-vampiire** [comment]
this is an edge case (users on multiple teams) that the system is not and will not be designed to handle.
