### ISSUE TITLE
I'm not adim of the repo of my team

### ISSUE THREAD

**Issue by angelfeliz** [Chingu-cohorts/voyage-wiki#83]
**_About You_**
- Team Name: bears-team-22
- Slack Name:  angel
- Timezone:  UTC-4

**_Issue Description & Expected Outcome:_** 
I'm not admin of the repository of my team
**_Symptoms:_**
don't have access to do anything
**_Steps to Recreate:_** 
go and check the team page please
**_Resolution:_** 
Talk with chance it was a problem with github team page of my team when he try to fix it

**Comment by tropicalchancer** [comment]
Hi @angelfeliz the issue was you haven't accepted your invite yet. Please go to your email connected to your github account and accept the repo invitation.
