### ISSUE TITLE
Please add new team member to our repo

### ISSUE THREAD

**Issue by sfiquet** [Chingu-cohorts/voyage-wiki#84]
**_About You_**
- Team Name: Bears-Team-19
- Slack Name: @Sylvie
- Timezone: UTC +0

**_Issue Description & Expected Outcome:_** 
Hi, I'm pretty sure this is already in your to-do list, but I thought it would make things easier with a ticket as a reminder.

Bears-19 has a new member. Could he be added to the GitHub team?

**_Resolution:_** 
Add @heyjp to our team repo

**Comment by tropicalchancer** [comment]
Hi @sfiquet! Added 🎉
