### ISSUE TITLE
Sick PM in Gecko-Team-7 -- Switch to new PM

### ISSUE THREAD

**Issue by Alexever17** [Chingu-cohorts/voyage-wiki#85]
**_About You_**
- Team Name:  Gecko Team 7
- Slack Name:  alexever17
- Timezone:  utc 0

**_Issue Description & Expected Outcome:_** 
I got very sick recently and am unable to further continue with the voyage, at least for a week but maybe more, so it is better for me to step down from the role of PM in the team and stop the voyage all together. 
I asked the team who would like to be PM, will tell soon

**_Resolution:_** 
The PM role should be switch to another teammember (name soon) and maybe an additional teammember if available would be good.

**Comment by tropicalchancer** [comment]
Thanks for making a ticket @Alexever17. I hope you are okay 🙏 

Please let me know when you talk to your team and we can go from there.

**Comment by Alexever17** [comment]
It was decided that the new pm will be @yiosh :)

**Comment by jdmedlock** [comment]
| Current Role | New Role |Slack Name | GitHub Name | email |
|:-------------|:----------|:------------|:--------------|:------|
| Team Member | PM | yiosh | yiosh | iinoted@gmail.com |

Routing to Wizard team for processing

**Comment by the-vampiire** [comment]
Yiosh is now PM of the team. left Alex as a member. feel better @Alexever17 .
