### ISSUE TITLE
Step down from the role of PM & this voyage -- team member is willing to take over

### ISSUE THREAD

**Issue by dianastanciu** [Chingu-cohorts/voyage-wiki#86]
**_About You_**
- Team Name: Gecko Team 28
- Slack Name: @dianastanciu
- Timezone: utc+2

**_Issue Description & Expected Outcome:_** 
I am extremely sorry to say that I need to step down from the role of PM and from this voyage altogether. When I applied for this voyage I miscalculated my actual availability and I ended up feeling overwhelmed (need to work on managing my time, I know). I've managed to get my peers through the act i, but I realise that if I continue with the sprints as well I will only do a lousy job and make them feel disappointed. 

**_Resolution:_** 
One of my peers was a PM in the previous voyage. I talked to him and luckily he said we is willing to take up the role of PM. His slack username is: @soreg .

**Comment by jdmedlock** [comment]
| Current Role | New Role |Slack Name | GitHub Name | email |
|:-------------|:----------|:------------|:--------------|:------|
| PM | N/a | dianastanciu | dianastanciu  | dianastanciu13@yahoo.co.uk  |
| Team Member | PM | soreg | soreg | S_Gravesen92@hotmail.com |

Removed dianastanciu from GitHub team.

Wizard team please make requested adjustments in the Backend.

**Comment by the-vampiire** [comment]
Diana has been removed from the team. Soreg has been promoted to PM.
