### ISSUE TITLE
Give access to a new teammate to a team repo

### ISSUE THREAD

**Issue by mar-bi** [Chingu-cohorts/voyage-wiki#87]
**_About You_**
- Team Name: bears-24
- Slack Name: mar-bi
- Timezone: GMT +2

**_Issue Description & Expected Outcome:_** 
We have got a new teammate - @Nedu. We need to give her access to our team repo.

**_Symptoms:_** positive
**_Steps to Recreate:_** 
**_Resolution:_** add @Nedu to members of bears-24

**Comment by jdmedlock** [comment]
| Current Role | New Role |Slack Name | GitHub Name | email |
|:-------------|:----------|:------------|:--------------|:------|
| N/a | Team Member | Nedu | nedu  | nedumrobert@gmail.com  |

Access granted to GitHub Bears-Team-24. 

Wizard team please make team adjustment. Move Nedu from Bears-Team-29 to Bears-Team-24

**Comment by tropicalchancer** [comment]
Ticket completed 🎉
