### ISSUE TITLE
Geckos Team 11 needs help!!!

### ISSUE THREAD

**Issue by CEOehis** [Chingu-cohorts/voyage-wiki#88]
**_About You_**
- Team Name: Geckos Team 11
- Slack Name: @ceo_ehis
- Timezone: UTC + 1

**_Issue Description & Expected Outcome:_** 
I wish to inform the facilitators that its not feasible for me to continue with this voyage due to pressing demands at work. I just can't cope with managing the project, save contributing my share to it and demands at work. 

My team currently has 2 people in the same time zone (UTC + 2) and one who is approx 7 hours behind them.  

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
We do not have any free agents for Geckos atm. Sent @CEOehis a message asking him to inform his team-mates so they can adapt as needed. Will make the changes in Wizard when @CEOehis gets back to me.

**Comment by tropicalchancer** [comment]
Note to self: might be best to split this team up as it does not look like they will survive as is

**Comment by tropicalchancer** [comment]
talked to asjas and will need to reach out to other members to see what the best course of action is

**Comment by tropicalchancer** [comment]
This team will be closed.
