### ISSUE TITLE
Geckos-Team-22 needs help

### ISSUE THREAD

**Issue by Skidragon** [Chingu-cohorts/voyage-wiki#89]
**_About You_**
- Team Name: Geckos-Team-22
- Slack Name: @Skidragon
- Timezone: ET 

**_Issue Description & Expected Outcome:_** 
Team is usually not available or at least a lot of work is not being done. @RiRiOG and @jonager seems like they are very busy at their jobs and @RiRiOG seems like she is trying by getting 1 hour or less per day and @jonager keeps promising that some work will be done but maybe his job is tiring him from doing the project. Not trying to blame them because real life can get in the way with family and other issues but It seems the team won't finish the MVP and I don't want to make it seem like I'm taking over the project and working solo which contradicts of what Chingu is about. My expected outcome is either to have another teammate who has more time to help out with the project or maybe split up the team into how much time commitment, they are willing to spend and put them into other groups who needs more people.
**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Added new member to team.
