### ISSUE TITLE
Geckos Team 06: Add 2 Members

### ISSUE THREAD

**Issue by kystrel** [Chingu-cohorts/voyage-wiki#90]
**_About You_**
- Team Name: Geckos 06
- Slack Name: JHart9
- Timezone: UTC -6

**_Issue Description & Expected Outcome:_** 
I have two members not added to the GitHub Repo yet and it totally slipped under the radar while we were planning the project. We need [Jahnava](https://github.com/Jahnava) and [pilarmireles22](https://github.com/pilarmireles22) added to the team so they can access the repo properly. Thank you!

Repo: https://github.com/chingu-voyage4/Geckos-Team-6

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by jdmedlock** [comment]
| Current Role | New Role |Slack Name | GitHub Name | email |
|:-------------|:----------|:------------|:--------------|:------|
| N/a | Team Member | Jahnava  | Jahnava  | jahnavalmt@gmail.com |
| N/a | Team Member | Pilar Mireles | pilarmireles22 | pilar.2m@hotmail.com |

Waiting on review by @tropicalchancer

**Comment by tropicalchancer** [comment]
Done
