### ISSUE TITLE
Bears21 - assign a new teamlead

### ISSUE THREAD

**Issue by jugglingjsons** [Chingu-cohorts/voyage-wiki#91]
**_About You_**
- Team Name: Bears21
- Slack Name: jadczak.d
- Timezone: gmt+1

**_Issue Description & Expected Outcome:_** 
Assign a new PM to Bears21 Team.
**_Symptoms:_**
Our current team lead is too busy with work/life and had to resign from participating.
**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by the-vampiire** [comment]
i need the current team lead email and the new team lead email

**Comment by jugglingjsons** [comment]
Current: vasile.razvan93@gmail.com aka raizen62 on github
New: jadczak.d@gmail.com aka jadczakd on github
