### ISSUE TITLE
Assign a new team member to Bears 21.

### ISSUE THREAD

**Issue by jugglingjsons** [Chingu-cohorts/voyage-wiki#92]
**_About You_**
- Team Name: Bears-team-21
- Slack Name: jadczak.d
- Timezone: gmt+1

**_Issue Description & Expected Outcome:_** 
Add a new team member - https://github.com/Asjas
**_Symptoms:_**
We're experiencing some inactivity and have https://github.com/Asjas has expressed will to join and help!
**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by jdmedlock** [comment]
| Current Role | New Role |Slack Name | GitHub Name | email |
|:-------------|:----------|:------------|:--------------|:------|
| N/a | Team Member | Asjas | Asjas | asjas@outlook.com |

Routing to Wizard team for processing

**Comment by the-vampiire** [comment]
added asjas to your team.

**Comment by jdmedlock** [comment]
Slack DM from Asjas:
```
Asjas [9:20 PM]
hi @Jdmedlock. When I spoke with Chance I said that I'll still stay for a while in my old team to see if they can start a project. If not then I'll leave.
```
