### ISSUE TITLE
Bears-Team-19: team member unable to do stand-up in Wizard

### ISSUE THREAD

**Issue by sfiquet** [Chingu-cohorts/voyage-wiki#93]
**_About You_**
- Team Name: Bears-Team-19
- Slack Name: @Sylvie
- Timezone: UTC +0

**_Issue Description & Expected Outcome:_** 
When I click on Team Standups, I expect to see the current team and their status. We lost a team member recently and gained a new one. The wizard still shows the old team composition.

**_Symptoms:_**
- When I click on Team Standups, the team list is out of date:  Burak T. is still listed and @heyjp is absent.
- Burak T.'s last stand-up is still showing. I'd rather it didn't, it just clutters the screen.
- More importantly @heyjp has posted his stand-up twice yesterday but it is not showing.

**_Note:_** 
In #wizard-issues @mattewburfield mentioned that Bears-Team-7 have a similar problem.

**Comment by jdmedlock** [comment]
| Current Role | New Role |Slack Name | GitHub Name | email |
|:-------------|:----------|:------------|:--------------|:------|
| N/a | Team Member | Heyjp | heyjp | jamieplayer@gmail.com |
| Team Member | N/a |  Burak T. | ucanfill |buraktilek@hotmail.com |

Routing to Wizard team for processing

**Comment by the-vampiire** [comment]
Burak has been removed. Jamie has been added as a member.
