### ISSUE TITLE
Inactive members

### ISSUE THREAD

**Issue by Rodielm** [Chingu-cohorts/voyage-wiki#94]
**_About You_**
- Team Name: Geckos-Team-35
- Slack Name: Rodiel Martinez
- Timezone: GMT-4

**_Issue Description & Expected Outcome:_** 
Inactive members

**_Symptoms:_**
I have more than two weeks trying to communicate with them about the project but lately they have been inactive. (Jorge Luis & ManuelR)

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by jdmedlock** [comment]
Review by @tropicalchancer is required. Information on the two missing team members below.

| Action | Current Role    | New Role |Slack Name | GitHub Name | email |
|:-------|:---------------|:----------|:------------|:--------------|:------|
| TBD     | Team Member | N/a           | Jorge Luis   | jorgeluisrezende| jorgeluisrezende94@gmail.com |
| TBD     | Team Member | N/a           | ManuelR      | Androbat        | manuelreyesjimenez11@gmail.com |
