### ISSUE TITLE
After switching teams, The Wizard doesn't recognize me

### ISSUE THREAD

**Issue by cewert** [Chingu-cohorts/voyage-wiki#95]
**_About You_**
- Team Name:  geckos-team-22
- Slack Name:  Charlie
- Timezone: EST

**_Issue Description & Expected Outcome:_** 

The slack Wizard doesn't know I'm a part of geckos 22, can you please add me? I was originally on geckos-5

**Comment by jdmedlock** [comment]
| Action | Current Role    | New Role |Slack Name | GitHub Name | email |
|:-------|:---------------|:----------|:------------|:--------------|:------|
| Wizard Fix     | Team Member | N/a           | Charlie   | cewert| cewert@gmail.com |

Routing to Wizard Team for diagnosis and resolution

**Comment by the-vampiire** [comment]
@cewert to be clear you are listed as the PM of Geckos Team 5.

are you remaining on that team as PM AND like to be added to Geckos Team 22
or are you leaving that team and switching to Geckos Team 22?

**Comment by cewert** [comment]
Geckos team 5 is dead. I reached out to Chance a week or so ago and he
assigned me to geckos 22.

**Comment by the-vampiire** [comment]
@cewert alright youre officially dropped from 5 and added as a member to 22. good luck

**Comment by cewert** [comment]
Thanks!
