### ISSUE TITLE
Team member couldn't continue voyage

### ISSUE THREAD

**Issue by SnGrimes** [Chingu-cohorts/voyage-wiki#96]
**_About You_**
- Team Name:  Geckos-Team-0
- Slack Name: @King Rex Orioko
- Timezone: UTC -06:00

**_Issue Description & Expected Outcome:_** 
Team member had to leave

**_Symptoms:_**
Team member participation has been sporadic. He realized he couldn't keep with the project with his current obligations.

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by tropicalchancer** [comment]
Thanks for letting us know @SnGrimes
