### ISSUE TITLE
Toucans-3 Inactive Member

### ISSUE THREAD

**Issue by fancyaction** [Chingu-cohorts/voyage-wiki#97]
**_About You_**
- Team Name: Toucans-Team-3
- Slack Name: fancyaction
- Timezone: UTC-5

**_Issue Description & Expected Outcome:_** Tony has yet to commit on Github, hasn't done a standup in two weeks and stopped communication all-together this week (despite being online). He mentioned at the start that he has a full-time job and busy family life, so this was always a possibility I accounted for and shouldn't impact our team. Regardless, there's no reason to keep him on the team. We wish him the best. For what it's worth, he was fun to talk to and I hope he gives Chingu another chance when things are less hectic in his life.

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_** Remove Tony from our Slack channel, standup wizard and GitHub.

**Comment by jdmedlock** [comment]
| Action | Current Role    | New Role |Slack Name | GitHub Name | email |
|:-------|:---------------|:----------|:------------|:--------------|:------|
| Remove member | Team Member | N/a           | Tony   | mrbrackins | tony@mrbrackins.com |

Wizard team please make the necessary adjustments
