### ISSUE TITLE
All team members left. Need to be changed to PM. 

### ISSUE THREAD

**Issue by jmaldia** [Chingu-cohorts/voyage-wiki#98]
**_About You_**
- Team Name: Team Toucans 5
- Slack Name: Jon
- Timezone: EST

**_Issue Description & Expected Outcome:_** 
All my team mates have left the team including the PM. Can my role be changed to PM so that I can submit the milestones? 

**_Symptoms:_**

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by jdmedlock** [comment]
| Action | Current Role    | New Role |Slack Name | GitHub Name | email |
|:-------|:---------------|:----------|:------------|:--------------|:------|
| Role Change | Team Member | PM           | Jon   | jmaldia | jon@maldia.net |

Wizard team please make the necessary changes

**Comment by jmaldia** [comment]
Wizard is still telling me that I'm not the PM.
