### ISSUE TITLE
Geckos team 15 - Team member unable to continue current voyage

### ISSUE THREAD

**Issue by Sosodope** [Chingu-cohorts/voyage-wiki#99]
**_About You_**
- Team Name: Geckos team 15 
- Slack Name: Jin
- Timezone: GMT + 8

**_Issue Description & Expected Outcome:_** 
Team member will not be participating in the project for the rest of the voyage

**_Symptoms:_**
She has not been able to commit enough time to the voyage due to work/family so she thinks it's best for the team to move on without her.

**_Steps to Recreate:_** 

**_Resolution:_**

**Comment by jdmedlock** [comment]
| Action | Current Role    | New Role |Slack Name | GitHub Name | email |
|:-------|:---------------|:----------|:------------|:--------------|:------|
| Remove | Team Member | N/a           | Jin   | jqhuang94 | jin.qiu94@gmail.com |
